/*
 *  generated by CSeq [ 0000 / 0000 ]
 * 
 *  instance version    {}
 *
 *  2019-04-30 10:40:59
 *
 *  params:
 *    -l datarace, -i ../DR-Experiments/truc/sndfile-tools-1.03_src_sndfile-jackplay_wip.c, --rounds 2, --unwind 2, --debug , 
 *
 */
#define __cs_MUTEX_INITIALIZER -1
#define __cs_COND_INITIALIZER -1
#define __cs_RWLOCK_INITIALIZER -1
#define __cs_BARRIER_SERIAL_THREAD 0
#define __cs_CANCEL_ASYNCHRONOUS 0
#define __cs_CANCEL_ENABLE 0
#define __cs_CANCEL_DEFERRED 0
#define __cs_CANCEL_DISABLE 0
#define __cs_CANCELED 0
#define __cs_CREATE_DETACHED 0
#define __cs_CREATE_JOINABLE 0
#define __cs_EXPLICIT_SCHED 0
#define __cs_INHERIT_SCHED 0
#define __cs_MUTEX_DEFAULT 0
#define __cs_MUTEX_ERRORCHECK 0
#define __cs_MUTEX_NORMAL 0
#define __cs_MUTEX_RECURSIVE 0
#define __cs_MUTEX_ROBUST 0
#define __cs_MUTEX_STALLED 0
#define __cs_ONCE_INIT 0
#define __cs_PRIO_INHERIT 0
#define __cs_PRIO_NONE 0
#define __cs_PRIO_PROTECT 0
#define __cs_PROCESS_SHARED 0
#define __cs_PROCESS_PRIVATE 0
#define __cs_SCOPE_PROCESS 0
#define __cs_SCOPE_SYSTEM 0
void *malloc(unsigned long int);
int __VERIFIER_nondet_int();
int nondet_int();
unsigned int __VERIFIER_nondet_uint();
unsigned int nondet_uint();
_Bool __VERIFIER_nondet_bool();
_Bool nondet_bool();
char __VERIFIER_nondet_char();
char nondet_char();
unsigned char __VERIFIER_nondet_uchar();
unsigned char nondet_uchar();
#define THREADS 1
#define ROUNDS 2
#define STOP_VOID(A) return;
#define STOP_NONVOID(A) return 0;
#define IF(T,A,B) if ((__cs_pc[T] > A) | (A >= __cs_pc_cs[T])) goto B; 

                                        unsigned __CPROVER_bitvector[1] __cs_active_thread[2] = {1};
                                        unsigned __CPROVER_bitvector[5] __cs_pc[2];
                                        unsigned __CPROVER_bitvector[6] __cs_pc_cs[2];
                                        unsigned __CPROVER_bitvector[1] __cs_last_thread;
                                        unsigned __CPROVER_bitvector[5] __cs_thread_lines[2] = {13, 20};
                                        void *__cs_safe_malloc(unsigned int __cs_size)
                                        {
                                        void *__cs_ptr = (malloc(__cs_size));
                                        return __cs_ptr;
                                        }
                                        void __cs_init_scalar(void *__cs_var, unsigned int __cs_size)
                                        {
                                        if (__cs_size == (sizeof(int)))
                                        *((int *) __cs_var) = nondet_int();
                                                else
                                                {
                                        __cs_var = malloc(__cs_size);
                                                }
                                        }
                                        void __CSEQ_message(char *__cs_message)
                                        {
                                                ;
                                        }
                                        typedef int __cs_t;
                                        void *__cs_threadargs[2];
                                        void *__cs_thread_joinargs[2];
                                        int __cs_create(__cs_t *__cs_new_thread_id, void *__cs_attr, void *(*__cs_thread_function)(void *), void *__cs_arg, int __cs_threadID)
                                        {
                                        if (__cs_threadID > THREADS)
                                                        return 0;
                                        *__cs_new_thread_id = __cs_threadID;
                                        __cs_active_thread[__cs_threadID] = 1;
                                        __cs_threadargs[__cs_threadID] = __cs_arg;
                                        __CSEQ_message("thread spawned");
                                        return 0;
                                        }
                                        int __cs_join(__cs_t __cs_id, void **__cs_value_ptr)
                                        {
                                        __CPROVER_assume(__cs_pc[__cs_id] == __cs_thread_lines[__cs_id]);
                                        *__cs_value_ptr = __cs_thread_joinargs[__cs_id];
                                        return 0;
                                        }
                                        int __cs_exit(void *__cs_value_ptr, unsigned int __cs_thread_index)
                                        {
                                        __cs_thread_joinargs[__cs_thread_index] = __cs_value_ptr;
                                        return 0;
                                        }
                                        int __cs_self(void)
                                        {
                                                return 1;
                                        }
                                        typedef int __cs_mutex_t;
                                        int __cs_mutex_init(__cs_mutex_t *__cs_m, int __cs_val)
                                        {
                                        *__cs_m = -1;
                                        return 0;
                                        }
                                        int __cs_mutex_destroy(__cs_mutex_t *__cs_mutex_to_destroy)
                                        {
                                        __CPROVER_assume((*__cs_mutex_to_destroy) != 0);
                                        __CPROVER_assume((*__cs_mutex_to_destroy) != (-2));
                                        __CPROVER_assume((*__cs_mutex_to_destroy) == (-1));
                                        *__cs_mutex_to_destroy = -2;
                                        __CSEQ_message("lock destroyed");
                                        return 0;
                                        }
                                        int __cs_mutex_lock(__cs_mutex_t *__cs_mutex_to_lock, unsigned __CPROVER_bitvector[1] __cs_thread_index)
                                        {
                                        __CPROVER_assume((*__cs_mutex_to_lock) != 0);
                                        __CPROVER_assume((*__cs_mutex_to_lock) != (-2));
                                        __CPROVER_assume((*__cs_mutex_to_lock) == (-1));
                                        *__cs_mutex_to_lock = __cs_thread_index + 1;
                                        __CSEQ_message("lock acquired");
                                        return 0;
                                        }
                                        int __cs_mutex_unlock(__cs_mutex_t *__cs_mutex_to_unlock, unsigned __CPROVER_bitvector[1] __cs_thread_index)
                                        {
                                        __CPROVER_assume((*__cs_mutex_to_unlock) != 0);
                                        __CPROVER_assume((*__cs_mutex_to_unlock) != (-2));
                                        __CPROVER_assume((*__cs_mutex_to_unlock) == (__cs_thread_index + 1));
                                        *__cs_mutex_to_unlock = -1;
                                        __CSEQ_message("lock released");
                                        return 0;
                                        }
                                        typedef int __cs_cond_t;
                                        int __cs_cond_init(__cs_cond_t *__cs_cond_to_init, void *__cs_attr)
                                        {
                                        *__cs_cond_to_init = -1;
                                        return 0;
                                        }
                                        int __cs_cond_destroy(__cs_cond_t *__cs_cond_to_destroy)
                                        {
                                        *__cs_cond_to_destroy = -2;
                                        return 0;
                                        }
                                        int __cs_cond_wait_1(__cs_cond_t *__cs_cond_to_wait_for, __cs_mutex_t *__cs_m, unsigned int __cs_thread_index)
                                        {
                                        __CPROVER_assume((*__cs_cond_to_wait_for) != 0);
                                        __CPROVER_assume((*__cs_cond_to_wait_for) != (-2));
                                        __cs_mutex_unlock(__cs_m, __cs_thread_index);
                                        return 0;
                                        }
                                        int __cs_cond_wait_2(__cs_cond_t *__cs_cond_to_wait_for, __cs_mutex_t *__cs_m, unsigned int __cs_thread_index)
                                        {
                                        __CPROVER_assume((*__cs_cond_to_wait_for) == 1);
                                        __cs_mutex_lock(__cs_m, __cs_thread_index);
                                        return 0;
                                        }
                                        int __cs_cond_signal(__cs_cond_t *__cs_cond_to_signal)
                                        {
                                        *__cs_cond_to_signal = 1;
                                        __CSEQ_message("conditional variable signal");
                                        return 0;
                                        }
                                        int __cs_cond_broadcast(__cs_cond_t *__cs_cond_to_broadcast)
                                        {
                                        *__cs_cond_to_broadcast = 1;
                                        __CSEQ_message("conditional variable broadcast");
                                        return 0;
                                        }
                                        typedef struct __cs_barrier_t
                                        {
                                        unsigned int init;
                                        unsigned int current;
                                        } __cs_barrier_t;
                                        int __cs_barrier_init(__cs_barrier_t *__cs_barrier_to_init, void *__cs_attr, unsigned int count)
                                        {
                                        __CPROVER_assume(count > 0);
                                        __cs_barrier_to_init->current = count;
                                        __cs_barrier_to_init->init = count;
                                        return 0;
                                        }
                                        int __cs_barrier_destroy(__cs_barrier_t *__cs_barrier_to_destroy)
                                        {
                                        __cs_barrier_to_destroy->init = -1;
                                        __cs_barrier_to_destroy->current = -1;
                                        return 0;
                                        }
                                        int __cs_barrier_wait_1(__cs_barrier_t *__cs_barrier_to_wait)
                                        {
                                        __CPROVER_assume(__cs_barrier_to_wait->init > 0);
                                        __cs_barrier_to_wait->current--;
                                        return 0;
                                        }
                                        int __cs_barrier_wait_2(__cs_barrier_t *__cs_barrier_to_wait)
                                        {
                                        __CPROVER_assume(__cs_barrier_to_wait->init > 0);
                                        __CPROVER_assume(__cs_barrier_to_wait->current == 0);
                                        __cs_barrier_to_wait->current = __cs_barrier_to_wait->init;
                                        return 0;
                                        }
                                        typedef int __cs_attr_t;
                                        struct sched_param
                                        {
                                        int sched_priority;
                                        };
                                        int __cs_attr_init(__cs_attr_t *t)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_destroy(__cs_attr_t *t)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getdetachstate(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getguardsize(const __cs_attr_t *t, unsigned int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getinheritsched(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getschedparam(const __cs_attr_t *t, struct sched_param *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getschedpolicy(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getscope(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getstackaddr(const __cs_attr_t *t, void **s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getstacksize(const __cs_attr_t *t, unsigned int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setdetachstate(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setguardsize(__cs_attr_t *t, unsigned int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setinheritsched(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setschedparam(__cs_attr_t *t, const struct sched_param *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setschedpolicy(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setscope(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setstackaddr(__cs_attr_t *t, void *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setstacksize(__cs_attr_t *t, unsigned int s)
                                        {
                                                return 0;
                                        }
                                        _Bool __cs_dataraceDetectionStarted = (0);
                                        _Bool __cs_dataraceSecondThread = (0);
                                        _Bool __cs_dataraceNotDetected = (1);
                                        _Bool __cs_dataraceContinue = (1);
                                        struct anonymous;
                                        struct anonymous$2;
                                        struct SF_INFO;
                                        struct SNDFILE_tag;
                                        struct _IO_FILE;
                                        struct _IO_marker;
                                        struct _jack_client;
                                        struct _jack_port;
                                        struct _thread_info;
                                        void *calloc(unsigned long int, unsigned long int);
                                        static void *disk_thread_0(void *__cs_param__arg);
                                        void exit(signed int);
                                        signed int fflush(struct _IO_FILE *);
                                        double fmod(double, double);
                                        signed int fprintf(struct _IO_FILE *, const char *, ...);
                                        void free(void *);
                                        signed int jack_activate(struct _jack_client *);
                                        signed int jack_client_close(struct _jack_client *);
                                        struct _jack_client *jack_client_new(const char *);
                                        signed int jack_connect(struct _jack_client *, const char *, const char *);
                                        unsigned int jack_get_sample_rate(struct _jack_client *);
                                        void jack_on_shutdown(struct _jack_client *, void (*)(void *), void *);
                                        void *jack_port_get_buffer(struct _jack_port *, unsigned int);
                                        const char *jack_port_name(const struct _jack_port *);
                                        struct _jack_port *jack_port_register(struct _jack_client *, const char *, const char *, unsigned long int, unsigned long int);
                                        struct anonymous$2 *jack_ringbuffer_create(unsigned long int);
                                        void jack_ringbuffer_free(struct anonymous$2 *);
                                        void jack_ringbuffer_get_write_vector(const struct anonymous$2 *, struct anonymous *);
                                        unsigned long int jack_ringbuffer_read(struct anonymous$2 *, char *, unsigned long int);
                                        void jack_ringbuffer_write_advance(struct anonymous$2 *, unsigned long int);
                                        signed int jack_set_process_callback(struct _jack_client *, signed int (*)(unsigned int, void *), void *);
                                        static void jack_shutdown(void *__cs_param__arg);
                                        void *memset(void *, signed int, unsigned long int);
                                        static void print_time(unsigned int __cs_param__pos, signed int __cs_param__jack_sr);
                                        static signed int process(unsigned int __cs_param__nframes, void *__cs_param__arg);
                                        signed int puts(const char *);
                                        signed int sf_close(struct SNDFILE_tag *);
                                        struct SNDFILE_tag *sf_open(const char *, signed int, struct SF_INFO *);
                                        signed long int sf_readf_float(struct SNDFILE_tag *, float *, signed long int);
                                        signed int snprintf(char *, unsigned long int, const char *, ...);
                                        signed int usleep(unsigned int);
                                        struct anonymous
                                        {
                                        char *buf;
                                        unsigned long int len;
                                        };
                                        struct anonymous$2
                                        {
                                        char *buf;
                                        unsigned long int write_ptr;
                                        unsigned long int read_ptr;
                                        unsigned long int size;
                                        unsigned long int size_mask;
                                        signed int mlocked;
                                        };
                                        struct SF_INFO
                                        {
                                        signed long int frames;
                                        signed int samplerate;
                                        signed int channels;
                                        signed int format;
                                        signed int sections;
                                        signed int seekable;
                                        };
                                        struct _IO_FILE
                                        {
                                        signed int _flags;
                                        char *_IO_read_ptr;
                                        char *_IO_read_end;
                                        char *_IO_read_base;
                                        char *_IO_write_base;
                                        char *_IO_write_ptr;
                                        char *_IO_write_end;
                                        char *_IO_buf_base;
                                        char *_IO_buf_end;
                                        char *_IO_save_base;
                                        char *_IO_backup_base;
                                        char *_IO_save_end;
                                        struct _IO_marker *_markers;
                                        struct _IO_FILE *_chain;
                                        signed int _fileno;
                                        signed int _flags2;
                                        signed long int _old_offset;
                                        unsigned short int _cur_column;
                                        signed char _vtable_offset;
                                        char _shortbuf[1l];
                                        void *_lock;
                                        signed long int _offset;
                                        void *__pad1;
                                        void *__pad2;
                                        void *__pad3;
                                        void *__pad4;
                                        unsigned long int __pad5;
                                        signed int _mode;
                                        char _unused2[(signed long int) ((sizeof(signed int)) * 5)];
                                        };
                                        struct _IO_marker
                                        {
                                        struct _IO_marker *_next;
                                        struct _IO_FILE *_sbuf;
                                        signed int _pos;
                                        };
                                        struct _thread_info
                                        {
                                        unsigned long int thread_id;
                                        struct SNDFILE_tag *sndfile;
                                        unsigned int pos;
                                        struct _jack_client *client;
                                        unsigned int channels;
                                        signed int can_process;
                                        signed int read_done;
                                        signed int play_done;
                                        };
                                        __cs_cond_t data_ready = (__cs_COND_INITIALIZER);
                                        __cs_mutex_t disk_thread_lock = (__cs_MUTEX_INITIALIZER);
                                        static struct _jack_port **output_port;
                                        static float **outs;
                                        static struct anonymous$2 *ringbuf;
                                        const unsigned long int sample_size = (sizeof(float));
                                        struct _IO_FILE *stderr;
                                        struct _IO_FILE *stdout;
                                        void *disk_thread_0(void *__cs_param_disk_thread_arg)
                                        {
                                        static struct _thread_info *__cs_local_disk_thread_info;
IF(1,0,tdisk_thread_0_1)
                                        __cs_local_disk_thread_info = (struct _thread_info *) __cs_param_disk_thread_arg;
                                        static signed long int __cs_local_disk_thread_buf_avail;
                                        static signed long int __cs_local_disk_thread_read_frames;
                                        static struct anonymous __cs_local_disk_thread_vec[2l];
                                        static unsigned long int __cs_local_disk_thread_bytes_per_frame;
tdisk_thread_0_1:
IF(1,1,tdisk_thread_0_2)
                                        if (((1 == __cs_pc[1]) & __cs_dataraceSecondThread) & (__CPROVER_get_field(&sample_size, "dr_write") || __CPROVER_get_field(__cs_local_disk_thread_info, "dr_write")))
                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_disk_thread_bytes_per_frame = sample_size * ((unsigned long int) (*__cs_local_disk_thread_info).channels);
                                        __cs_setcanceltype(1, (signed int *) 0);
tdisk_thread_0_2:
IF(1,2,tdisk_thread_0_3)
                                        __cs_mutex_lock(&disk_thread_lock, 1);
                                        if (!((_Bool) 1))
                                                {
                                        goto __exit_loop_1;
                                                        ;
                                                }
                                        ;
                                                {
tdisk_thread_0_3:
IF(1,3,tdisk_thread_0_4)
                                        if (((3 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&ringbuf, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        jack_ringbuffer_get_write_vector(ringbuf, __cs_local_disk_thread_vec);
                                        __cs_local_disk_thread_read_frames = (signed long int) 0;
                                        ;
                                                        ;
                                        static _Bool __cs_local_disk_thread___cs_tmp_if_cond_0;
                                        __cs_local_disk_thread___cs_tmp_if_cond_0 = !(__cs_local_disk_thread_vec[0l].len == 0ul);
                                        if (__cs_local_disk_thread___cs_tmp_if_cond_0)
                                                        {
                                        __cs_local_disk_thread_buf_avail = (signed long int) (__cs_local_disk_thread_vec[(signed long int) 0].len / __cs_local_disk_thread_bytes_per_frame);
tdisk_thread_0_4:
IF(1,4,tdisk_thread_0_5)
                                        if (((4 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(__cs_local_disk_thread_info, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_disk_thread_read_frames = sf_readf_float((*__cs_local_disk_thread_info).sndfile, (float *) __cs_local_disk_thread_vec[(signed long int) 0].buf, __cs_local_disk_thread_buf_avail);
                                        ;
                                                                ;
                                        static _Bool __cs_local_disk_thread___cs_tmp_if_cond_1;
                                        __cs_local_disk_thread___cs_tmp_if_cond_1 = !(__cs_local_disk_thread_vec[1l].len == 0ul);
                                        if (__cs_local_disk_thread___cs_tmp_if_cond_1)
                                                                {
                                        __cs_local_disk_thread_buf_avail = (signed long int) (__cs_local_disk_thread_vec[(signed long int) 1].len / __cs_local_disk_thread_bytes_per_frame);
                                        static signed long int __cs_local_disk_thread_return_value_sf_readf_float$1;
tdisk_thread_0_5:
IF(1,5,tdisk_thread_0_6)
                                        if (((5 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(__cs_local_disk_thread_info, "dr_write"))
                                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_disk_thread_return_value_sf_readf_float$1 = sf_readf_float((*__cs_local_disk_thread_info).sndfile, (float *) __cs_local_disk_thread_vec[(signed long int) 1].buf, __cs_local_disk_thread_buf_avail);
                                        __cs_local_disk_thread_read_frames = __cs_local_disk_thread_read_frames + __cs_local_disk_thread_return_value_sf_readf_float$1;
                                                                }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 6);
                                                                ;
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 6);
                                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_disk_thread___cs_tmp_if_cond_2;
                                        __cs_local_disk_thread___cs_tmp_if_cond_2 = __cs_local_disk_thread_read_frames == 0l;
                                        if (__cs_local_disk_thread___cs_tmp_if_cond_2)
                                                        {
                                        goto __exit_loop_1;
                                                                ;
                                                        }
                                        ;
tdisk_thread_0_6:
IF(1,6,tdisk_thread_0_7)
                                        if (((6 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&ringbuf, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        jack_ringbuffer_write_advance(ringbuf, ((unsigned long int) __cs_local_disk_thread_read_frames) * __cs_local_disk_thread_bytes_per_frame);
tdisk_thread_0_7:
                                        if (((7 == __cs_pc_cs[1]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                        {
                                        __CPROVER_set_field(__cs_local_disk_thread_info, "dr_write", 1);
                                                        }
IF(1,7,tdisk_thread_0_8)
                                        if (((7 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(__cs_local_disk_thread_info, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        (*__cs_local_disk_thread_info).can_process = 1;
tdisk_thread_0_8:
IF(1,8,tdisk_thread_0_9)
                                        __cs_cond_wait_1(&data_ready, &disk_thread_lock, 1);
tdisk_thread_0_9:
IF(1,9,tdisk_thread_0_10)
                                        __cs_cond_wait_2(&data_ready, &disk_thread_lock, 1);
                                        ;
                                                        ;
                                                }
                                        ;
                                        if (!((_Bool) 1))
                                                {
                                        goto __exit_loop_1;
                                                        ;
                                                }
                                        ;
                                                {
tdisk_thread_0_10:
IF(1,10,tdisk_thread_0_11)
                                        if (((10 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&ringbuf, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        jack_ringbuffer_get_write_vector(ringbuf, __cs_local_disk_thread_vec);
                                        __cs_local_disk_thread_read_frames = (signed long int) 0;
                                        ;
                                                        ;
                                        static _Bool __cs_local_disk_thread___cs_tmp_if_cond_0;
                                        __cs_local_disk_thread___cs_tmp_if_cond_0 = !(__cs_local_disk_thread_vec[0l].len == 0ul);
                                        if (__cs_local_disk_thread___cs_tmp_if_cond_0)
                                                        {
                                        __cs_local_disk_thread_buf_avail = (signed long int) (__cs_local_disk_thread_vec[(signed long int) 0].len / __cs_local_disk_thread_bytes_per_frame);
tdisk_thread_0_11:
IF(1,11,tdisk_thread_0_12)
                                        if (((11 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(__cs_local_disk_thread_info, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_disk_thread_read_frames = sf_readf_float((*__cs_local_disk_thread_info).sndfile, (float *) __cs_local_disk_thread_vec[(signed long int) 0].buf, __cs_local_disk_thread_buf_avail);
                                        ;
                                                                ;
                                        static _Bool __cs_local_disk_thread___cs_tmp_if_cond_1;
                                        __cs_local_disk_thread___cs_tmp_if_cond_1 = !(__cs_local_disk_thread_vec[1l].len == 0ul);
                                        if (__cs_local_disk_thread___cs_tmp_if_cond_1)
                                                                {
                                        __cs_local_disk_thread_buf_avail = (signed long int) (__cs_local_disk_thread_vec[(signed long int) 1].len / __cs_local_disk_thread_bytes_per_frame);
                                        static signed long int __cs_local_disk_thread_return_value_sf_readf_float$1;
tdisk_thread_0_12:
IF(1,12,tdisk_thread_0_13)
                                        if (((12 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(__cs_local_disk_thread_info, "dr_write"))
                                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_disk_thread_return_value_sf_readf_float$1 = sf_readf_float((*__cs_local_disk_thread_info).sndfile, (float *) __cs_local_disk_thread_vec[(signed long int) 1].buf, __cs_local_disk_thread_buf_avail);
                                        __cs_local_disk_thread_read_frames = __cs_local_disk_thread_read_frames + __cs_local_disk_thread_return_value_sf_readf_float$1;
                                                                }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 13);
                                                                ;
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 13);
                                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_disk_thread___cs_tmp_if_cond_2;
                                        __cs_local_disk_thread___cs_tmp_if_cond_2 = __cs_local_disk_thread_read_frames == 0l;
                                        if (__cs_local_disk_thread___cs_tmp_if_cond_2)
                                                        {
                                        goto __exit_loop_1;
                                                                ;
                                                        }
                                        ;
tdisk_thread_0_13:
IF(1,13,tdisk_thread_0_14)
                                        if (((13 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&ringbuf, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        jack_ringbuffer_write_advance(ringbuf, ((unsigned long int) __cs_local_disk_thread_read_frames) * __cs_local_disk_thread_bytes_per_frame);
tdisk_thread_0_14:
                                        if (((14 == __cs_pc_cs[1]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                        {
                                        __CPROVER_set_field(__cs_local_disk_thread_info, "dr_write", 1);
                                                        }
IF(1,14,tdisk_thread_0_15)
                                        if (((14 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(__cs_local_disk_thread_info, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        (*__cs_local_disk_thread_info).can_process = 1;
tdisk_thread_0_15:
IF(1,15,tdisk_thread_0_16)
                                        __cs_cond_wait_1(&data_ready, &disk_thread_lock, 1);
tdisk_thread_0_16:
IF(1,16,tdisk_thread_0_17)
                                        __cs_cond_wait_2(&data_ready, &disk_thread_lock, 1);
                                        ;
                                                        ;
                                                }
                                        ;
tdisk_thread_0_17:
IF(1,17,tdisk_thread_0_18)
                                        __CPROVER_assume(!((_Bool) 1));
                                        __exit_loop_1:
                                                __CPROVER_assume(__cs_pc_cs[1] >= 18);
                                        ;
                                                ;
tdisk_thread_0_18:
                                        if (((18 == __cs_pc_cs[1]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                {
                                        __CPROVER_set_field(__cs_local_disk_thread_info, "dr_write", 1);
                                                }
IF(1,18,tdisk_thread_0_19)
                                        if (((18 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(__cs_local_disk_thread_info, "dr_write"))
                                                        __cs_dataraceNotDetected = 0;
                                        (*__cs_local_disk_thread_info).read_done = 1;
tdisk_thread_0_19:
IF(1,19,tdisk_thread_0_20)
                                        __cs_mutex_unlock(&disk_thread_lock, 1);
                                        goto __exit_disk_thread;
                                                ;
                                        __exit_disk_thread:
                                                __CPROVER_assume(__cs_pc_cs[1] >= 20);
                                        ;
                                                ;
tdisk_thread_0_20: 
                                        __cs_exit(0, 1);
                                        }
                                        signed int main_thread(void)
                                        {
                                                signed int __cs_param_main_narg;
                                                char **__cs_param_main_args;
IF(0,0,tmain_1)
                                        static struct SNDFILE_tag *__cs_local_main_sndfile;
                                        static struct SF_INFO __cs_local_main_sndfileinfo;
                                        static struct _jack_client *__cs_local_main_client;
                                        static struct _thread_info __cs_local_main_info;
                                        static signed int __cs_local_main_i;
                                        static signed int __cs_local_main_jack_sr;
                                        ;
                                                ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_3;
                                        __cs_local_main___cs_tmp_if_cond_3 = !(__cs_param_main_narg >= 2);
                                        if (__cs_local_main___cs_tmp_if_cond_3)
                                                {
                                        fprintf(stderr, "no soundfile given\n");
                                        goto __exit_main;
                                                        ;
                                                }
                                                else
                                                {
                                        __cs_local_main_client = jack_client_new("jackplay");
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_4;
                                        __cs_local_main___cs_tmp_if_cond_4 = __cs_local_main_client == ((struct _jack_client *) 0);
                                        if (__cs_local_main___cs_tmp_if_cond_4)
                                                        {
                                        fprintf(stderr, "Jack server not running?\n");
                                        goto __exit_main;
                                                                ;
                                                        }
                                                        else
                                                        {
                                        static unsigned int __cs_local_main_return_value_jack_get_sample_rate$1;
                                        __cs_local_main_return_value_jack_get_sample_rate$1 = jack_get_sample_rate(__cs_local_main_client);
                                        __cs_local_main_jack_sr = (signed int) __cs_local_main_return_value_jack_get_sample_rate$1;
                                        __cs_local_main_sndfileinfo.format = 0;
                                        __cs_local_main_sndfile = sf_open(__cs_param_main_args[(signed long int) 1], 16, &__cs_local_main_sndfileinfo);
                                        ;
                                                                ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_5;
                                        __cs_local_main___cs_tmp_if_cond_5 = __cs_local_main_sndfile == ((struct SNDFILE_tag *) 0);
                                        if (__cs_local_main___cs_tmp_if_cond_5)
                                                                {
                                        fprintf(stderr, "Could not open soundfile '%s'\n", __cs_param_main_args[(signed long int) 1]);
                                        goto __exit_main;
                                                                        ;
                                                                }
                                                                else
                                                                {
                                        fprintf(stderr, "Channels    : %d\nSample rate : %d Hz\nDuration    : ", __cs_local_main_sndfileinfo.channels, __cs_local_main_sndfileinfo.samplerate);
                                                                        {
                                        static unsigned int __cs_param_print_time_pos;
                                        __cs_param_print_time_pos = (unsigned int) __cs_local_main_sndfileinfo.frames;
                                        static signed int __cs_param_print_time_jack_sr;
                                        __cs_param_print_time_jack_sr = __cs_local_main_sndfileinfo.samplerate;
                                        static float __cs_local_print_time_sec;
                                        __cs_local_print_time_sec = (float) (((double) __cs_param_print_time_pos) / (1.0 * ((double) __cs_param_print_time_jack_sr)));
                                        static signed int __cs_local_print_time_min;
                                        __cs_local_print_time_min = (signed int) (((double) __cs_local_print_time_sec) / 60.0);
                                        static double __cs_local_print_time_return_value_fmod$1;
                                        __cs_local_print_time_return_value_fmod$1 = fmod((double) __cs_local_print_time_sec, 60.0);
                                        fprintf(stderr, "%02d:%05.2f", __cs_local_print_time_min, __cs_local_print_time_return_value_fmod$1);
                                        __exit__print_time_1:
                                                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                                                ;
                                                                        }
                                        ;
                                        fprintf(stderr, "\n");
                                        ;
                                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_6;
                                        __cs_local_main___cs_tmp_if_cond_6 = !(__cs_local_main_sndfileinfo.samplerate == __cs_local_main_jack_sr);
                                        if (__cs_local_main___cs_tmp_if_cond_6)
                                                                        {
                                        fprintf(stderr, "Warning: samplerate of soundfile (%d Hz) does not match jack server (%d Hz).\n", __cs_local_main_sndfileinfo.samplerate, __cs_local_main_jack_sr);
                                                                        }
                                        ;
                                        memset((void *) (&__cs_local_main_info), 0, sizeof(struct _thread_info));
                                        __cs_local_main_info.can_process = 0;
                                        __cs_local_main_info.read_done = 0;
                                        __cs_local_main_info.play_done = 0;
                                        __cs_local_main_info.sndfile = __cs_local_main_sndfile;
                                        __cs_local_main_info.channels = (unsigned int) __cs_local_main_sndfileinfo.channels;
                                        __cs_local_main_info.client = __cs_local_main_client;
                                        __cs_local_main_info.pos = (unsigned int) 0;
                                        jack_set_process_callback(__cs_local_main_client, process, (void *) (&__cs_local_main_info));
                                        jack_on_shutdown(__cs_local_main_client, jack_shutdown, 0);
                                        static void *__cs_local_main_return_value_calloc$2;
                                        __cs_local_main_return_value_calloc$2 = calloc((unsigned long int) __cs_local_main_sndfileinfo.channels, sizeof(struct _jack_port *));
                                        output_port = (struct _jack_port **) __cs_local_main_return_value_calloc$2;
                                        static void *__cs_local_main_return_value_calloc$3;
                                        __cs_local_main_return_value_calloc$3 = calloc((unsigned long int) __cs_local_main_sndfileinfo.channels, sizeof(float *));
                                        outs = (float **) __cs_local_main_return_value_calloc$3;
                                        __cs_local_main_i = 0;
                                        ;
                                                                        ;
                                        if (!(!(__cs_local_main_i >= __cs_local_main_sndfileinfo.channels)))
                                                                        {
                                        goto __exit_loop_2;
                                                                                ;
                                                                        }
                                        ;
                                                                        {
                                        static char *__cs_local_main_name;
                                        __cs_local_main_name = (char *) __cs_safe_malloc((sizeof(char)) * 16l);
                                        snprintf(__cs_local_main_name, sizeof(char [16l]), "out_%d", __cs_local_main_i + 1);
                                        output_port[(signed long int) __cs_local_main_i] = jack_port_register(__cs_local_main_client, __cs_local_main_name, "32 bit float mono audio", (unsigned long int) 2, (unsigned long int) 0);
                                                                        }
                                        ;
                                        __cs_local_main_i = __cs_local_main_i + 1;
                                        if (!(!(__cs_local_main_i >= __cs_local_main_sndfileinfo.channels)))
                                                                        {
                                        goto __exit_loop_2;
                                                                                ;
                                                                        }
                                        ;
                                                                        {
                                        static char *__cs_local_main_name;
                                        __cs_local_main_name = (char *) __cs_safe_malloc((sizeof(char)) * 16l);
                                        snprintf(__cs_local_main_name, sizeof(char [16l]), "out_%d", __cs_local_main_i + 1);
                                        output_port[(signed long int) __cs_local_main_i] = jack_port_register(__cs_local_main_client, __cs_local_main_name, "32 bit float mono audio", (unsigned long int) 2, (unsigned long int) 0);
                                                                        }
                                        ;
                                        __cs_local_main_i = __cs_local_main_i + 1;
                                        __CPROVER_assume(!(!(__cs_local_main_i >= __cs_local_main_sndfileinfo.channels)));
                                        __exit_loop_2:
                                                                        __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                                        ;
                                        ringbuf = jack_ringbuffer_create((sizeof(float)) * ((unsigned long int) (1 << 16)));
                                        memset((void *) (*ringbuf).buf, 0, (*ringbuf).size);
                                        static signed int __cs_local_main_return_value_jack_activate$4;
                                        __cs_local_main_return_value_jack_activate$4 = jack_activate(__cs_local_main_client);
                                        ;
                                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_7;
                                        __cs_local_main___cs_tmp_if_cond_7 = !(__cs_local_main_return_value_jack_activate$4 == 0);
                                        if (__cs_local_main___cs_tmp_if_cond_7)
                                                                        {
                                        fprintf(stderr, "Cannot activate client.\n");
                                        goto __exit_main;
                                                                                ;
                                                                        }
                                                                        else
                                                                        {
                                        __cs_local_main_i = 0;
                                        ;
                                                                                ;
                                        if (!(!(__cs_local_main_i >= __cs_local_main_sndfileinfo.channels)))
                                                                                {
                                        goto __exit_loop_3;
                                                                                        ;
                                                                                }
                                        ;
                                                                                {
                                        static char *__cs_local_main_main$$1$$6$$1$$name;
                                        __cs_local_main_main$$1$$6$$1$$name = (char *) __cs_safe_malloc((sizeof(char)) * 64l);
                                        snprintf(__cs_local_main_main$$1$$6$$1$$name, sizeof(char [64l]), "alsa_pcm:playback_%d", __cs_local_main_i + 1);
                                        static const char *__cs_local_main_return_value_jack_port_name$5;
                                        __cs_local_main_return_value_jack_port_name$5 = jack_port_name(output_port[(signed long int) __cs_local_main_i]);
                                        static signed int __cs_local_main_return_value_jack_connect$6;
                                        __cs_local_main_return_value_jack_connect$6 = jack_connect(__cs_local_main_client, __cs_local_main_return_value_jack_port_name$5, __cs_local_main_main$$1$$6$$1$$name);
                                        ;
                                                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_8;
                                        __cs_local_main___cs_tmp_if_cond_8 = !(__cs_local_main_return_value_jack_connect$6 == 0);
                                        if (__cs_local_main___cs_tmp_if_cond_8)
                                                                                        {
                                        fprintf(stderr, "Cannot connect output port %d (%s).\n", __cs_local_main_i, (const void *) __cs_local_main_main$$1$$6$$1$$name);
                                                                                        }
                                        ;
                                                                                }
                                        ;
                                        __cs_local_main_i = __cs_local_main_i + 1;
                                        if (!(!(__cs_local_main_i >= __cs_local_main_sndfileinfo.channels)))
                                                                                {
                                        goto __exit_loop_3;
                                                                                        ;
                                                                                }
                                        ;
                                                                                {
                                        static char *__cs_local_main_main$$1$$6$$1$$name;
                                        __cs_local_main_main$$1$$6$$1$$name = (char *) __cs_safe_malloc((sizeof(char)) * 64l);
                                        snprintf(__cs_local_main_main$$1$$6$$1$$name, sizeof(char [64l]), "alsa_pcm:playback_%d", __cs_local_main_i + 1);
                                        static const char *__cs_local_main_return_value_jack_port_name$5;
                                        __cs_local_main_return_value_jack_port_name$5 = jack_port_name(output_port[(signed long int) __cs_local_main_i]);
                                        static signed int __cs_local_main_return_value_jack_connect$6;
                                        __cs_local_main_return_value_jack_connect$6 = jack_connect(__cs_local_main_client, __cs_local_main_return_value_jack_port_name$5, __cs_local_main_main$$1$$6$$1$$name);
                                        ;
                                                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_8;
                                        __cs_local_main___cs_tmp_if_cond_8 = !(__cs_local_main_return_value_jack_connect$6 == 0);
                                        if (__cs_local_main___cs_tmp_if_cond_8)
                                                                                        {
                                        fprintf(stderr, "Cannot connect output port %d (%s).\n", __cs_local_main_i, (const void *) __cs_local_main_main$$1$$6$$1$$name);
                                                                                        }
                                        ;
                                                                                }
                                        ;
                                        __cs_local_main_i = __cs_local_main_i + 1;
                                        __CPROVER_assume(!(!(__cs_local_main_i >= __cs_local_main_sndfileinfo.channels)));
                                        __exit_loop_3:
                                                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                                                ;
                                        __cs_create(&__cs_local_main_info.thread_id, (const __cs_attr_t *) 0, disk_thread_0, (void *) (&__cs_local_main_info), 1);
                                        if (!(__cs_local_main_info.play_done == 0))
                                                                                {
                                        goto __exit_loop_4;
                                                                                        ;
                                                                                }
                                        ;
                                                                                {
tmain_1:
IF(0,1,tmain_2)
                                        if (((1 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&stderr, "dr_write"))
                                                                                                __cs_dataraceNotDetected = 0;
                                        fprintf(stderr, "\r-> ");
                                                                                        {
                                        static unsigned int __cs_param_print_time_pos;
                                        __cs_param_print_time_pos = __cs_local_main_info.pos;
                                        static signed int __cs_param_print_time_jack_sr;
                                        __cs_param_print_time_jack_sr = __cs_local_main_jack_sr;
                                        static float __cs_local_print_time_sec;
                                        __cs_local_print_time_sec = (float) (((double) __cs_param_print_time_pos) / (1.0 * ((double) __cs_param_print_time_jack_sr)));
                                        static signed int __cs_local_print_time_min;
                                        __cs_local_print_time_min = (signed int) (((double) __cs_local_print_time_sec) / 60.0);
                                        static double __cs_local_print_time_return_value_fmod$1;
                                        __cs_local_print_time_return_value_fmod$1 = fmod((double) __cs_local_print_time_sec, 60.0);
tmain_2:
IF(0,2,tmain_3)
                                        if (((2 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&stderr, "dr_write"))
                                                                                                        __cs_dataraceNotDetected = 0;
                                        fprintf(stderr, "%02d:%05.2f", __cs_local_print_time_min, __cs_local_print_time_return_value_fmod$1);
                                        __exit__print_time_2_0:
                                                                                                __CPROVER_assume(__cs_pc_cs[0] >= 3);
                                        ;
                                                                                                ;
                                                                                        }
                                        ;
tmain_3:
IF(0,3,tmain_4)
                                        if (((3 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&stdout, "dr_write"))
                                                                                                __cs_dataraceNotDetected = 0;
                                        fflush(stdout);
                                        usleep((unsigned int) 50000);
                                                                                }
                                        ;
                                        if (!(__cs_local_main_info.play_done == 0))
                                                                                {
                                        goto __exit_loop_4;
                                                                                        ;
                                                                                }
                                        ;
                                                                                {
tmain_4:
IF(0,4,tmain_5)
                                        if (((4 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&stderr, "dr_write"))
                                                                                                __cs_dataraceNotDetected = 0;
                                        fprintf(stderr, "\r-> ");
                                                                                        {
                                        static unsigned int __cs_param_print_time_pos;
                                        __cs_param_print_time_pos = __cs_local_main_info.pos;
                                        static signed int __cs_param_print_time_jack_sr;
                                        __cs_param_print_time_jack_sr = __cs_local_main_jack_sr;
                                        static float __cs_local_print_time_sec;
                                        __cs_local_print_time_sec = (float) (((double) __cs_param_print_time_pos) / (1.0 * ((double) __cs_param_print_time_jack_sr)));
                                        static signed int __cs_local_print_time_min;
                                        __cs_local_print_time_min = (signed int) (((double) __cs_local_print_time_sec) / 60.0);
                                        static double __cs_local_print_time_return_value_fmod$1;
                                        __cs_local_print_time_return_value_fmod$1 = fmod((double) __cs_local_print_time_sec, 60.0);
tmain_5:
IF(0,5,tmain_6)
                                        if (((5 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&stderr, "dr_write"))
                                                                                                        __cs_dataraceNotDetected = 0;
                                        fprintf(stderr, "%02d:%05.2f", __cs_local_print_time_min, __cs_local_print_time_return_value_fmod$1);
                                        __exit__print_time_2_1:
                                                                                                __CPROVER_assume(__cs_pc_cs[0] >= 6);
                                        ;
                                                                                                ;
                                                                                        }
                                        ;
tmain_6:
IF(0,6,tmain_7)
                                        if (((6 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&stdout, "dr_write"))
                                                                                                __cs_dataraceNotDetected = 0;
                                        fflush(stdout);
                                        usleep((unsigned int) 50000);
                                                                                }
                                        ;
tmain_7:
IF(0,7,tmain_8)
                                        __CPROVER_assume(!(__cs_local_main_info.play_done == 0));
                                        __exit_loop_4:
                                                                                __CPROVER_assume(__cs_pc_cs[0] >= 8);
                                        ;
                                                                                ;
tmain_8:
IF(0,8,tmain_9)
                                        jack_client_close(__cs_local_main_client);
tmain_9:
IF(0,9,tmain_10)
                                        if (((9 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&ringbuf, "dr_write"))
                                                                                        __cs_dataraceNotDetected = 0;
                                        jack_ringbuffer_free(ringbuf);
tmain_10:
IF(0,10,tmain_11)
                                        sf_close(__cs_local_main_sndfile);
tmain_11:
IF(0,11,tmain_12)
                                        if (((11 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&outs, "dr_write"))
                                                                                        __cs_dataraceNotDetected = 0;
                                        free((void *) outs);
tmain_12:
IF(0,12,tmain_13)
                                        if (((12 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&output_port, "dr_write"))
                                                                                        __cs_dataraceNotDetected = 0;
                                        free((void *) output_port);
                                        puts("");
                                        goto __exit_main;
                                                                                ;
                                                                        }
                                        __CPROVER_assume(__cs_pc_cs[0] >= 13);
                                                                        ;
                                                                }
                                        __CPROVER_assume(__cs_pc_cs[0] >= 13);
                                                                ;
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[0] >= 13);
                                                        ;
                                                }
                                        __CPROVER_assume(__cs_pc_cs[0] >= 13);
                                                ;
                                        __exit_main:
                                                __CPROVER_assume(__cs_pc_cs[0] >= 13);
                                        ;
                                                ;
tmain_13: 
                                        __cs_exit(0, 0);
                                        }
                                        int main(void)
                                        {
                                        __CPROVER_field_decl_global("dr_write", (_Bool) 0);
                                        unsigned __CPROVER_bitvector[2] __cs_dr_ts;
                                        __CPROVER_assume(__cs_dr_ts <= 3);
/* round  0 */
/* main */
                                        unsigned __CPROVER_bitvector[4] __cs_tmp_t0_r0;
                                        __cs_pc_cs[0] = __cs_tmp_t0_r0;
                                        __CPROVER_assume(__cs_pc_cs[0] > 0);
                                        __CPROVER_assume(__cs_pc_cs[0] <= 13);
                                        if (__cs_dr_ts == 0)
                                                        __cs_dataraceDetectionStarted = 1;
                                        main_thread();
                                        if (__cs_dataraceDetectionStarted)
                                                        __cs_dataraceSecondThread = 1;
                                        __cs_pc[0] = __cs_pc_cs[0];
/* disk_thread_0 */
                                        unsigned __CPROVER_bitvector[5] __cs_tmp_t1_r0;
                                        if (__cs_dataraceContinue & __cs_active_thread[1])
                                                {
                                        __cs_pc_cs[1] = __cs_tmp_t1_r0;
                                        __CPROVER_assume(__cs_pc_cs[1] <= 20);
                                        if (__cs_dr_ts == 1)
                                                                __cs_dataraceDetectionStarted = 1;
                                        disk_thread_0(__cs_threadargs[1]);
                                        if (__cs_dataraceSecondThread & (__cs_tmp_t1_r0 > __cs_pc[1]))
                                                                __cs_dataraceContinue = 0;
                                        if (__cs_dataraceDetectionStarted)
                                                                __cs_dataraceSecondThread = 1;
                                        __cs_pc[1] = __cs_pc_cs[1];
                                                }
/* round  1 */
/* main */
                                        unsigned __CPROVER_bitvector[4] __cs_tmp_t0_r1;
                                        if (((__cs_dr_ts > 0) & __cs_dataraceContinue) & __cs_active_thread[0])
                                                {
                                        __cs_pc_cs[0] = __cs_pc[0] + __cs_tmp_t0_r1;
                                        __CPROVER_assume(__cs_pc_cs[0] >= __cs_pc[0]);
                                        __CPROVER_assume(__cs_pc_cs[0] <= 13);
                                        if (__cs_dr_ts == 2)
                                                                __cs_dataraceDetectionStarted = 1;
                                        main_thread();
                                        if (__cs_dataraceSecondThread & (__cs_tmp_t0_r1 > __cs_pc[0]))
                                                                __cs_dataraceContinue = 0;
                                        if (__cs_dataraceDetectionStarted)
                                                                __cs_dataraceSecondThread = 1;
                                        __cs_pc[0] = __cs_pc_cs[0];
                                                }
/* disk_thread_0 */
                                        unsigned __CPROVER_bitvector[5] __cs_tmp_t1_r1;
                                        if (((__cs_dr_ts > 1) & __cs_dataraceContinue) & __cs_active_thread[1])
                                                {
                                        __cs_pc_cs[1] = __cs_pc[1] + __cs_tmp_t1_r1;
                                        __CPROVER_assume(__cs_pc_cs[1] >= __cs_pc[1]);
                                        __CPROVER_assume(__cs_pc_cs[1] <= 20);
                                        if (__cs_dr_ts == 3)
                                                                __cs_dataraceDetectionStarted = 1;
                                        disk_thread_0(__cs_threadargs[1]);
                                        if (__cs_dataraceSecondThread & (__cs_tmp_t1_r1 > __cs_pc[1]))
                                                                __cs_dataraceContinue = 0;
                                        if (__cs_dataraceDetectionStarted)
                                                                __cs_dataraceSecondThread = 1;
                                        __cs_pc[1] = __cs_pc_cs[1];
                                                }
                                        unsigned __CPROVER_bitvector[4] __cs_tmp_t0_r2;
                                        if (((__cs_dr_ts > 0) & __cs_dataraceContinue) & __cs_active_thread[0])
                                                {
                                        __cs_pc_cs[0] = __cs_pc[0] + __cs_tmp_t0_r2;
                                        __CPROVER_assume(__cs_pc_cs[0] >= __cs_pc[0]);
                                        __CPROVER_assume(__cs_pc_cs[0] <= 13);
                                        main_thread();
                                                }
                                        __CPROVER_assert(__cs_dataraceNotDetected, "Data race failure");
                                        return 0;
                                        }
                                        
