/*
 *  generated by CSeq [ 0000 / 0000 ]
 * 
 *  instance version    {}
 *
 *  2019-04-30 10:41:34
 *
 *  params:
 *    -l datarace, -i ../DR-Experiments/truc/wysihtml-0.13_wysidocbookdaemon_wip.c, --rounds 2, --unwind 2, --debug , 
 *
 */
#define __cs_MUTEX_INITIALIZER -1
#define __cs_COND_INITIALIZER -1
#define __cs_RWLOCK_INITIALIZER -1
#define __cs_BARRIER_SERIAL_THREAD 0
#define __cs_CANCEL_ASYNCHRONOUS 0
#define __cs_CANCEL_ENABLE 0
#define __cs_CANCEL_DEFERRED 0
#define __cs_CANCEL_DISABLE 0
#define __cs_CANCELED 0
#define __cs_CREATE_DETACHED 0
#define __cs_CREATE_JOINABLE 0
#define __cs_EXPLICIT_SCHED 0
#define __cs_INHERIT_SCHED 0
#define __cs_MUTEX_DEFAULT 0
#define __cs_MUTEX_ERRORCHECK 0
#define __cs_MUTEX_NORMAL 0
#define __cs_MUTEX_RECURSIVE 0
#define __cs_MUTEX_ROBUST 0
#define __cs_MUTEX_STALLED 0
#define __cs_ONCE_INIT 0
#define __cs_PRIO_INHERIT 0
#define __cs_PRIO_NONE 0
#define __cs_PRIO_PROTECT 0
#define __cs_PROCESS_SHARED 0
#define __cs_PROCESS_PRIVATE 0
#define __cs_SCOPE_PROCESS 0
#define __cs_SCOPE_SYSTEM 0
void *malloc(unsigned long int);
int __VERIFIER_nondet_int();
int nondet_int();
unsigned int __VERIFIER_nondet_uint();
unsigned int nondet_uint();
_Bool __VERIFIER_nondet_bool();
_Bool nondet_bool();
char __VERIFIER_nondet_char();
char nondet_char();
unsigned char __VERIFIER_nondet_uchar();
unsigned char nondet_uchar();
#define THREADS 1
#define ROUNDS 2
#define STOP_VOID(A) return;
#define STOP_NONVOID(A) return 0;
#define IF(T,A,B) if ((__cs_pc[T] > A) | (A >= __cs_pc_cs[T])) goto B; 

                                        unsigned __CPROVER_bitvector[1] __cs_active_thread[2] = {1};
                                        unsigned __CPROVER_bitvector[6] __cs_pc[2];
                                        unsigned __CPROVER_bitvector[7] __cs_pc_cs[2];
                                        unsigned __CPROVER_bitvector[1] __cs_last_thread;
                                        unsigned __CPROVER_bitvector[6] __cs_thread_lines[2] = {26, 46};
                                        void *__cs_safe_malloc(unsigned int __cs_size)
                                        {
                                        void *__cs_ptr = (malloc(__cs_size));
                                        return __cs_ptr;
                                        }
                                        void __cs_init_scalar(void *__cs_var, unsigned int __cs_size)
                                        {
                                        if (__cs_size == (sizeof(int)))
                                        *((int *) __cs_var) = nondet_int();
                                                else
                                                {
                                        __cs_var = malloc(__cs_size);
                                                }
                                        }
                                        void __CSEQ_message(char *__cs_message)
                                        {
                                                ;
                                        }
                                        typedef int __cs_t;
                                        void *__cs_threadargs[2];
                                        void *__cs_thread_joinargs[2];
                                        int __cs_create(__cs_t *__cs_new_thread_id, void *__cs_attr, void *(*__cs_thread_function)(void *), void *__cs_arg, int __cs_threadID)
                                        {
                                        if (__cs_threadID > THREADS)
                                                        return 0;
                                        *__cs_new_thread_id = __cs_threadID;
                                        __cs_active_thread[__cs_threadID] = 1;
                                        __cs_threadargs[__cs_threadID] = __cs_arg;
                                        __CSEQ_message("thread spawned");
                                        return 0;
                                        }
                                        int __cs_join(__cs_t __cs_id, void **__cs_value_ptr)
                                        {
                                        __CPROVER_assume(__cs_pc[__cs_id] == __cs_thread_lines[__cs_id]);
                                        *__cs_value_ptr = __cs_thread_joinargs[__cs_id];
                                        return 0;
                                        }
                                        int __cs_exit(void *__cs_value_ptr, unsigned int __cs_thread_index)
                                        {
                                        __cs_thread_joinargs[__cs_thread_index] = __cs_value_ptr;
                                        return 0;
                                        }
                                        int __cs_self(void)
                                        {
                                                return 1;
                                        }
                                        typedef int __cs_mutex_t;
                                        int __cs_mutex_init(__cs_mutex_t *__cs_m, int __cs_val)
                                        {
                                        *__cs_m = -1;
                                        return 0;
                                        }
                                        int __cs_mutex_destroy(__cs_mutex_t *__cs_mutex_to_destroy)
                                        {
                                        __CPROVER_assume((*__cs_mutex_to_destroy) != 0);
                                        __CPROVER_assume((*__cs_mutex_to_destroy) != (-2));
                                        __CPROVER_assume((*__cs_mutex_to_destroy) == (-1));
                                        *__cs_mutex_to_destroy = -2;
                                        __CSEQ_message("lock destroyed");
                                        return 0;
                                        }
                                        int __cs_mutex_lock(__cs_mutex_t *__cs_mutex_to_lock, unsigned __CPROVER_bitvector[1] __cs_thread_index)
                                        {
                                        __CPROVER_assume((*__cs_mutex_to_lock) != 0);
                                        __CPROVER_assume((*__cs_mutex_to_lock) != (-2));
                                        __CPROVER_assume((*__cs_mutex_to_lock) == (-1));
                                        *__cs_mutex_to_lock = __cs_thread_index + 1;
                                        __CSEQ_message("lock acquired");
                                        return 0;
                                        }
                                        int __cs_mutex_unlock(__cs_mutex_t *__cs_mutex_to_unlock, unsigned __CPROVER_bitvector[1] __cs_thread_index)
                                        {
                                        __CPROVER_assume((*__cs_mutex_to_unlock) != 0);
                                        __CPROVER_assume((*__cs_mutex_to_unlock) != (-2));
                                        __CPROVER_assume((*__cs_mutex_to_unlock) == (__cs_thread_index + 1));
                                        *__cs_mutex_to_unlock = -1;
                                        __CSEQ_message("lock released");
                                        return 0;
                                        }
                                        typedef int __cs_cond_t;
                                        int __cs_cond_init(__cs_cond_t *__cs_cond_to_init, void *__cs_attr)
                                        {
                                        *__cs_cond_to_init = -1;
                                        return 0;
                                        }
                                        int __cs_cond_destroy(__cs_cond_t *__cs_cond_to_destroy)
                                        {
                                        *__cs_cond_to_destroy = -2;
                                        return 0;
                                        }
                                        int __cs_cond_wait_1(__cs_cond_t *__cs_cond_to_wait_for, __cs_mutex_t *__cs_m, unsigned int __cs_thread_index)
                                        {
                                        __CPROVER_assume((*__cs_cond_to_wait_for) != 0);
                                        __CPROVER_assume((*__cs_cond_to_wait_for) != (-2));
                                        __cs_mutex_unlock(__cs_m, __cs_thread_index);
                                        return 0;
                                        }
                                        int __cs_cond_wait_2(__cs_cond_t *__cs_cond_to_wait_for, __cs_mutex_t *__cs_m, unsigned int __cs_thread_index)
                                        {
                                        __CPROVER_assume((*__cs_cond_to_wait_for) == 1);
                                        __cs_mutex_lock(__cs_m, __cs_thread_index);
                                        return 0;
                                        }
                                        int __cs_cond_signal(__cs_cond_t *__cs_cond_to_signal)
                                        {
                                        *__cs_cond_to_signal = 1;
                                        __CSEQ_message("conditional variable signal");
                                        return 0;
                                        }
                                        int __cs_cond_broadcast(__cs_cond_t *__cs_cond_to_broadcast)
                                        {
                                        *__cs_cond_to_broadcast = 1;
                                        __CSEQ_message("conditional variable broadcast");
                                        return 0;
                                        }
                                        typedef struct __cs_barrier_t
                                        {
                                        unsigned int init;
                                        unsigned int current;
                                        } __cs_barrier_t;
                                        int __cs_barrier_init(__cs_barrier_t *__cs_barrier_to_init, void *__cs_attr, unsigned int count)
                                        {
                                        __CPROVER_assume(count > 0);
                                        __cs_barrier_to_init->current = count;
                                        __cs_barrier_to_init->init = count;
                                        return 0;
                                        }
                                        int __cs_barrier_destroy(__cs_barrier_t *__cs_barrier_to_destroy)
                                        {
                                        __cs_barrier_to_destroy->init = -1;
                                        __cs_barrier_to_destroy->current = -1;
                                        return 0;
                                        }
                                        int __cs_barrier_wait_1(__cs_barrier_t *__cs_barrier_to_wait)
                                        {
                                        __CPROVER_assume(__cs_barrier_to_wait->init > 0);
                                        __cs_barrier_to_wait->current--;
                                        return 0;
                                        }
                                        int __cs_barrier_wait_2(__cs_barrier_t *__cs_barrier_to_wait)
                                        {
                                        __CPROVER_assume(__cs_barrier_to_wait->init > 0);
                                        __CPROVER_assume(__cs_barrier_to_wait->current == 0);
                                        __cs_barrier_to_wait->current = __cs_barrier_to_wait->init;
                                        return 0;
                                        }
                                        typedef int __cs_attr_t;
                                        struct sched_param
                                        {
                                        int sched_priority;
                                        };
                                        int __cs_attr_init(__cs_attr_t *t)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_destroy(__cs_attr_t *t)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getdetachstate(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getguardsize(const __cs_attr_t *t, unsigned int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getinheritsched(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getschedparam(const __cs_attr_t *t, struct sched_param *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getschedpolicy(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getscope(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getstackaddr(const __cs_attr_t *t, void **s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getstacksize(const __cs_attr_t *t, unsigned int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setdetachstate(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setguardsize(__cs_attr_t *t, unsigned int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setinheritsched(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setschedparam(__cs_attr_t *t, const struct sched_param *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setschedpolicy(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setscope(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setstackaddr(__cs_attr_t *t, void *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setstacksize(__cs_attr_t *t, unsigned int s)
                                        {
                                                return 0;
                                        }
                                        _Bool __cs_dataraceDetectionStarted = (0);
                                        _Bool __cs_dataraceSecondThread = (0);
                                        _Bool __cs_dataraceNotDetected = (1);
                                        _Bool __cs_dataraceContinue = (1);
                                        struct _IO_FILE;
                                        struct _IO_marker;
                                        signed int asprintf(char ** restrict , const char *, ...);
                                        signed int atoi(const char *);
                                        signed int close(signed int);
                                        double difftime(signed long int, signed long int);
                                        void exit(signed int);
                                        signed int fork(void);
                                        signed int fprintf(struct _IO_FILE *, const char *, ...);
                                        void free(void *);
                                        char *getenv(const char *);
                                        signed int getopt(signed int, char * const *, const char *);
                                        signed int loopexec_0(void);
                                        signed int mkstemp(char *);
                                        void new_temporary_filename(void);
                                        signed int printf(const char *, ...);
                                        signed int scanf(const char *, ...);
                                        unsigned int sleep(unsigned int);
                                        char *strdup(const char *);
                                        signed int system(const char *);
                                        signed long int time(signed long int *);
                                        signed int unlink(const char *);
                                        signed int waitpid(signed int, signed int *, signed int);
                                        struct _IO_FILE
                                        {
                                        signed int _flags;
                                        char *_IO_read_ptr;
                                        char *_IO_read_end;
                                        char *_IO_read_base;
                                        char *_IO_write_base;
                                        char *_IO_write_ptr;
                                        char *_IO_write_end;
                                        char *_IO_buf_base;
                                        char *_IO_buf_end;
                                        char *_IO_save_base;
                                        char *_IO_backup_base;
                                        char *_IO_save_end;
                                        struct _IO_marker *_markers;
                                        struct _IO_FILE *_chain;
                                        signed int _fileno;
                                        signed int _flags2;
                                        signed long int _old_offset;
                                        unsigned short int _cur_column;
                                        signed char _vtable_offset;
                                        char _shortbuf[1l];
                                        void *_lock;
                                        signed long int _offset;
                                        void *__pad1;
                                        void *__pad2;
                                        void *__pad3;
                                        void *__pad4;
                                        unsigned long int __pad5;
                                        signed int _mode;
                                        char _unused2[(signed long int) ((sizeof(signed int)) * 5)];
                                        };
                                        struct _IO_marker
                                        {
                                        struct _IO_marker *_next;
                                        struct _IO_FILE *_sbuf;
                                        signed int _pos;
                                        };
                                        char *currentfile = ((char *) 0);
                                        signed long int last_input;
                                        const char *mozillacmdline = ((const char *) 0);
                                        char *optarg;
                                        char *optional = ((char *) 0);
                                        __cs_mutex_t plock = (__cs_MUTEX_INITIALIZER);
                                        struct _IO_FILE *stderr;
                                        char *temporary_filename = ((char *) 0);
                                        signed int wait_sleeptime = (3);
                                        char *xsltstylesheet = ("/usr/share/xml/docbook/stylesheet/ldp/html/tldp-one-page.xsl");
                                        signed int loopexec_0(void *__cs_param_loopexec___cs_unused)
                                        {
                                        static signed long int __cs_local_loopexec_last_display;
IF(1,0,tloopexec_0_1)
                                        __cs_local_loopexec_last_display = time((signed long int *) 0);
                                        static signed long int __cs_local_loopexec_current_time;
                                        static signed int __cs_local_loopexec_doit;
                                        static double __cs_local_loopexec_return_value_difftime$2;
                                        static double __cs_local_loopexec_return_value_difftime$1;
                                        if (!((_Bool) 1))
                                                {
                                        goto __exit_loop_1;
                                                        ;
                                                }
                                        ;
                                                {
                                        sleep((unsigned int) 1);
tloopexec_0_1:
IF(1,1,tloopexec_0_2)
                                        __cs_mutex_lock(&plock, 1);
                                        __cs_local_loopexec_current_time = time((signed long int *) 0);
                                        __cs_local_loopexec_doit = 0;
                                        static double __cs_local_loopexec_return_value_difftime$4;
tloopexec_0_2:
IF(1,2,tloopexec_0_3)
                                        if (((2 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&last_input, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_loopexec_return_value_difftime$4 = difftime(last_input, __cs_local_loopexec_last_display);
                                        ;
                                                        ;
                                        static _Bool __cs_local_loopexec___cs_tmp_if_cond_0;
                                        __cs_local_loopexec___cs_tmp_if_cond_0 = __cs_local_loopexec_return_value_difftime$4 > 0.000000;
                                        if (__cs_local_loopexec___cs_tmp_if_cond_0)
                                                        {
                                        static double __cs_local_loopexec_return_value_difftime$3;
tloopexec_0_3:
IF(1,3,tloopexec_0_4)
                                        if (((3 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&last_input, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_loopexec_return_value_difftime$3 = difftime(__cs_local_loopexec_current_time, last_input);
                                        ;
                                                                ;
                                        static _Bool __cs_local_loopexec___cs_tmp_if_cond_1;
tloopexec_0_4:
IF(1,4,tloopexec_0_5)
                                        if (((4 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&wait_sleeptime, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_loopexec___cs_tmp_if_cond_1 = __cs_local_loopexec_return_value_difftime$3 > ((double) wait_sleeptime);
                                        if (__cs_local_loopexec___cs_tmp_if_cond_1)
                                                                {
                                        __cs_local_loopexec_doit = 1;
                                                                }
                                                                else
                                                                {
                                        __cs_local_loopexec_return_value_difftime$2 = difftime(__cs_local_loopexec_current_time, __cs_local_loopexec_last_display);
                                        ;
                                                                        ;
                                        static _Bool __cs_local_loopexec___cs_tmp_if_cond_2;
                                        __cs_local_loopexec___cs_tmp_if_cond_2 = __cs_local_loopexec_return_value_difftime$2 > 20.000000;
                                        if (__cs_local_loopexec___cs_tmp_if_cond_2)
                                                                        {
tloopexec_0_5:
IF(1,5,tloopexec_0_6)
                                        if (((5 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&last_input, "dr_write"))
                                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_loopexec_return_value_difftime$1 = difftime(__cs_local_loopexec_current_time, last_input);
                                        ;
                                                                                ;
                                        static _Bool __cs_local_loopexec___cs_tmp_if_cond_3;
                                        __cs_local_loopexec___cs_tmp_if_cond_3 = __cs_local_loopexec_return_value_difftime$1 > 0.000000;
                                        if (__cs_local_loopexec___cs_tmp_if_cond_3)
                                                                                {
                                        __cs_local_loopexec_doit = 1;
                                                                                }
                                        ;
                                                                        }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 6);
                                                                        ;
                                                                }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 6);
                                                                ;
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 6);
                                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_loopexec___cs_tmp_if_cond_4;
                                        __cs_local_loopexec___cs_tmp_if_cond_4 = !(__cs_local_loopexec_doit == 0);
                                        if (__cs_local_loopexec___cs_tmp_if_cond_4)
                                                        {
                                        ;
                                                                ;
                                        static _Bool __cs_local_loopexec___cs_tmp_if_cond_5;
tloopexec_0_6:
IF(1,6,tloopexec_0_7)
                                        if (((6 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&currentfile, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_loopexec___cs_tmp_if_cond_5 = !(currentfile == ((char *) 0));
                                        if (__cs_local_loopexec___cs_tmp_if_cond_5)
                                                                {
                                        static char *__cs_local_loopexec_buf;
tloopexec_0_7:
IF(1,7,tloopexec_0_8)
                                        __cs_local_loopexec_buf = (char *) 0;
                                                                        {
                                        static signed int __cs_local_new_temporary_filename_fd;
                                        ;
                                                                                ;
                                        static _Bool __cs_local_new_temporary_filename___cs_tmp_if_cond_19;
tloopexec_0_8:
IF(1,8,tloopexec_0_9)
                                        if (((8 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&temporary_filename, "dr_write"))
                                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_new_temporary_filename___cs_tmp_if_cond_19 = !(temporary_filename == ((char *) 0));
                                        if (__cs_local_new_temporary_filename___cs_tmp_if_cond_19)
                                                                                {
                                        static signed int __cs_local_new_temporary_filename_return_value_fork$1;
                                        __cs_local_new_temporary_filename_return_value_fork$1 = fork();
                                        ;
                                                                                        ;
                                        static _Bool __cs_local_new_temporary_filename___cs_tmp_if_cond_20;
                                        __cs_local_new_temporary_filename___cs_tmp_if_cond_20 = __cs_local_new_temporary_filename_return_value_fork$1 == 0;
                                        if (__cs_local_new_temporary_filename___cs_tmp_if_cond_20)
                                                                                        {
                                        sleep((unsigned int) 10);
tloopexec_0_9:
IF(1,9,tloopexec_0_10)
                                        if (((9 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&temporary_filename, "dr_write"))
                                                                                                        __cs_dataraceNotDetected = 0;
                                        unlink(temporary_filename);
                                        exit(0);
                                                                                        }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 10);
                                                                                        ;
tloopexec_0_10:
IF(1,10,tloopexec_0_11)
                                        if (((10 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&temporary_filename, "dr_write"))
                                                                                                __cs_dataraceNotDetected = 0;
                                        free((void *) temporary_filename);
tloopexec_0_11:
                                        if (((11 == __cs_pc_cs[1]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                                                        {
                                        __CPROVER_set_field(&temporary_filename, "dr_write", 1);
                                                                                        }
IF(1,11,tloopexec_0_12)
                                        if (((11 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&temporary_filename, "dr_write"))
                                                                                                __cs_dataraceNotDetected = 0;
                                        temporary_filename = (char *) 0;
                                                                                }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 12);
                                                                                ;
                                        static char *__cs_local_new_temporary_filename_return_value_getenv$2;
tloopexec_0_12:
IF(1,12,tloopexec_0_13)
                                        __cs_local_new_temporary_filename_return_value_getenv$2 = getenv("TMPDIR");
tloopexec_0_13:
IF(1,13,tloopexec_0_14)
                                        asprintf(&temporary_filename, "%s/wysidocbookXXXXXX", ((_Bool) __cs_local_new_temporary_filename_return_value_getenv$2) ? (__cs_local_new_temporary_filename_return_value_getenv$2) : ("/tmp"));
tloopexec_0_14:
IF(1,14,tloopexec_0_15)
                                        if (((14 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&temporary_filename, "dr_write"))
                                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_new_temporary_filename_fd = mkstemp(temporary_filename);
                                        close(__cs_local_new_temporary_filename_fd);
                                        waitpid(-1, (signed int *) 0, 1);
                                        __exit__new_temporary_filename_1_0:
                                                                                __CPROVER_assume(__cs_pc_cs[1] >= 15);
                                        ;
                                                                                ;
                                                                        }
                                        ;
tloopexec_0_15:
IF(1,15,tloopexec_0_16)
                                        if (((15 == __cs_pc[1]) & __cs_dataraceSecondThread) & ((__CPROVER_get_field(&xsltstylesheet, "dr_write") || __CPROVER_get_field(&currentfile, "dr_write")) || __CPROVER_get_field(&temporary_filename, "dr_write")))
                                                                                __cs_dataraceNotDetected = 0;
                                        asprintf(&__cs_local_loopexec_buf, "xsltproc --novalid %s %s > %s", xsltstylesheet, currentfile, temporary_filename);
tloopexec_0_16:
IF(1,16,tloopexec_0_17)
                                        printf("invoke: %s\n", __cs_local_loopexec_buf);
tloopexec_0_17:
IF(1,17,tloopexec_0_18)
                                        system(__cs_local_loopexec_buf);
tloopexec_0_18:
IF(1,18,tloopexec_0_19)
                                        free((void *) __cs_local_loopexec_buf);
tloopexec_0_19:
IF(1,19,tloopexec_0_20)
                                        if (((19 == __cs_pc[1]) & __cs_dataraceSecondThread) & ((__CPROVER_get_field(&mozillacmdline, "dr_write") || __CPROVER_get_field(&temporary_filename, "dr_write")) || __CPROVER_get_field(&optional, "dr_write")))
                                                                                __cs_dataraceNotDetected = 0;
                                        asprintf(&__cs_local_loopexec_buf, mozillacmdline, temporary_filename, optional);
tloopexec_0_20:
IF(1,20,tloopexec_0_21)
                                        system(__cs_local_loopexec_buf);
                                        printf("invocation complete\n");
tloopexec_0_21:
IF(1,21,tloopexec_0_22)
                                        free((void *) __cs_local_loopexec_buf);
                                        __cs_local_loopexec_last_display = __cs_local_loopexec_current_time;
                                                                }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 22);
                                                                ;
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 22);
                                                        ;
tloopexec_0_22:
IF(1,22,tloopexec_0_23)
                                        __cs_mutex_unlock(&plock, 1);
                                                }
                                        ;
                                        if (!((_Bool) 1))
                                                {
                                        goto __exit_loop_1;
                                                        ;
                                                }
                                        ;
                                                {
                                        sleep((unsigned int) 1);
tloopexec_0_23:
IF(1,23,tloopexec_0_24)
                                        __cs_mutex_lock(&plock, 1);
                                        __cs_local_loopexec_current_time = time((signed long int *) 0);
                                        __cs_local_loopexec_doit = 0;
                                        static double __cs_local_loopexec_return_value_difftime$4;
tloopexec_0_24:
IF(1,24,tloopexec_0_25)
                                        if (((24 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&last_input, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_loopexec_return_value_difftime$4 = difftime(last_input, __cs_local_loopexec_last_display);
                                        ;
                                                        ;
                                        static _Bool __cs_local_loopexec___cs_tmp_if_cond_0;
                                        __cs_local_loopexec___cs_tmp_if_cond_0 = __cs_local_loopexec_return_value_difftime$4 > 0.000000;
                                        if (__cs_local_loopexec___cs_tmp_if_cond_0)
                                                        {
                                        static double __cs_local_loopexec_return_value_difftime$3;
tloopexec_0_25:
IF(1,25,tloopexec_0_26)
                                        if (((25 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&last_input, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_loopexec_return_value_difftime$3 = difftime(__cs_local_loopexec_current_time, last_input);
                                        ;
                                                                ;
                                        static _Bool __cs_local_loopexec___cs_tmp_if_cond_1;
tloopexec_0_26:
IF(1,26,tloopexec_0_27)
                                        if (((26 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&wait_sleeptime, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_loopexec___cs_tmp_if_cond_1 = __cs_local_loopexec_return_value_difftime$3 > ((double) wait_sleeptime);
                                        if (__cs_local_loopexec___cs_tmp_if_cond_1)
                                                                {
                                        __cs_local_loopexec_doit = 1;
                                                                }
                                                                else
                                                                {
                                        __cs_local_loopexec_return_value_difftime$2 = difftime(__cs_local_loopexec_current_time, __cs_local_loopexec_last_display);
                                        ;
                                                                        ;
                                        static _Bool __cs_local_loopexec___cs_tmp_if_cond_2;
                                        __cs_local_loopexec___cs_tmp_if_cond_2 = __cs_local_loopexec_return_value_difftime$2 > 20.000000;
                                        if (__cs_local_loopexec___cs_tmp_if_cond_2)
                                                                        {
tloopexec_0_27:
IF(1,27,tloopexec_0_28)
                                        if (((27 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&last_input, "dr_write"))
                                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_loopexec_return_value_difftime$1 = difftime(__cs_local_loopexec_current_time, last_input);
                                        ;
                                                                                ;
                                        static _Bool __cs_local_loopexec___cs_tmp_if_cond_3;
                                        __cs_local_loopexec___cs_tmp_if_cond_3 = __cs_local_loopexec_return_value_difftime$1 > 0.000000;
                                        if (__cs_local_loopexec___cs_tmp_if_cond_3)
                                                                                {
                                        __cs_local_loopexec_doit = 1;
                                                                                }
                                        ;
                                                                        }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 28);
                                                                        ;
                                                                }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 28);
                                                                ;
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 28);
                                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_loopexec___cs_tmp_if_cond_4;
                                        __cs_local_loopexec___cs_tmp_if_cond_4 = !(__cs_local_loopexec_doit == 0);
                                        if (__cs_local_loopexec___cs_tmp_if_cond_4)
                                                        {
                                        ;
                                                                ;
                                        static _Bool __cs_local_loopexec___cs_tmp_if_cond_5;
tloopexec_0_28:
IF(1,28,tloopexec_0_29)
                                        if (((28 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&currentfile, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_loopexec___cs_tmp_if_cond_5 = !(currentfile == ((char *) 0));
                                        if (__cs_local_loopexec___cs_tmp_if_cond_5)
                                                                {
                                        static char *__cs_local_loopexec_buf;
tloopexec_0_29:
IF(1,29,tloopexec_0_30)
                                        __cs_local_loopexec_buf = (char *) 0;
                                                                        {
                                        static signed int __cs_local_new_temporary_filename_fd;
                                        ;
                                                                                ;
                                        static _Bool __cs_local_new_temporary_filename___cs_tmp_if_cond_19;
tloopexec_0_30:
IF(1,30,tloopexec_0_31)
                                        if (((30 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&temporary_filename, "dr_write"))
                                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_new_temporary_filename___cs_tmp_if_cond_19 = !(temporary_filename == ((char *) 0));
                                        if (__cs_local_new_temporary_filename___cs_tmp_if_cond_19)
                                                                                {
                                        static signed int __cs_local_new_temporary_filename_return_value_fork$1;
                                        __cs_local_new_temporary_filename_return_value_fork$1 = fork();
                                        ;
                                                                                        ;
                                        static _Bool __cs_local_new_temporary_filename___cs_tmp_if_cond_20;
                                        __cs_local_new_temporary_filename___cs_tmp_if_cond_20 = __cs_local_new_temporary_filename_return_value_fork$1 == 0;
                                        if (__cs_local_new_temporary_filename___cs_tmp_if_cond_20)
                                                                                        {
                                        sleep((unsigned int) 10);
tloopexec_0_31:
IF(1,31,tloopexec_0_32)
                                        if (((31 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&temporary_filename, "dr_write"))
                                                                                                        __cs_dataraceNotDetected = 0;
                                        unlink(temporary_filename);
                                        exit(0);
                                                                                        }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 32);
                                                                                        ;
tloopexec_0_32:
IF(1,32,tloopexec_0_33)
                                        if (((32 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&temporary_filename, "dr_write"))
                                                                                                __cs_dataraceNotDetected = 0;
                                        free((void *) temporary_filename);
tloopexec_0_33:
                                        if (((33 == __cs_pc_cs[1]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                                                        {
                                        __CPROVER_set_field(&temporary_filename, "dr_write", 1);
                                                                                        }
IF(1,33,tloopexec_0_34)
                                        if (((33 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&temporary_filename, "dr_write"))
                                                                                                __cs_dataraceNotDetected = 0;
                                        temporary_filename = (char *) 0;
                                                                                }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 34);
                                                                                ;
                                        static char *__cs_local_new_temporary_filename_return_value_getenv$2;
tloopexec_0_34:
IF(1,34,tloopexec_0_35)
                                        __cs_local_new_temporary_filename_return_value_getenv$2 = getenv("TMPDIR");
tloopexec_0_35:
IF(1,35,tloopexec_0_36)
                                        asprintf(&temporary_filename, "%s/wysidocbookXXXXXX", ((_Bool) __cs_local_new_temporary_filename_return_value_getenv$2) ? (__cs_local_new_temporary_filename_return_value_getenv$2) : ("/tmp"));
tloopexec_0_36:
IF(1,36,tloopexec_0_37)
                                        if (((36 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&temporary_filename, "dr_write"))
                                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_local_new_temporary_filename_fd = mkstemp(temporary_filename);
                                        close(__cs_local_new_temporary_filename_fd);
                                        waitpid(-1, (signed int *) 0, 1);
                                        __exit__new_temporary_filename_1_1:
                                                                                __CPROVER_assume(__cs_pc_cs[1] >= 37);
                                        ;
                                                                                ;
                                                                        }
                                        ;
tloopexec_0_37:
IF(1,37,tloopexec_0_38)
                                        if (((37 == __cs_pc[1]) & __cs_dataraceSecondThread) & ((__CPROVER_get_field(&xsltstylesheet, "dr_write") || __CPROVER_get_field(&currentfile, "dr_write")) || __CPROVER_get_field(&temporary_filename, "dr_write")))
                                                                                __cs_dataraceNotDetected = 0;
                                        asprintf(&__cs_local_loopexec_buf, "xsltproc --novalid %s %s > %s", xsltstylesheet, currentfile, temporary_filename);
tloopexec_0_38:
IF(1,38,tloopexec_0_39)
                                        printf("invoke: %s\n", __cs_local_loopexec_buf);
tloopexec_0_39:
IF(1,39,tloopexec_0_40)
                                        system(__cs_local_loopexec_buf);
tloopexec_0_40:
IF(1,40,tloopexec_0_41)
                                        free((void *) __cs_local_loopexec_buf);
tloopexec_0_41:
IF(1,41,tloopexec_0_42)
                                        if (((41 == __cs_pc[1]) & __cs_dataraceSecondThread) & ((__CPROVER_get_field(&mozillacmdline, "dr_write") || __CPROVER_get_field(&temporary_filename, "dr_write")) || __CPROVER_get_field(&optional, "dr_write")))
                                                                                __cs_dataraceNotDetected = 0;
                                        asprintf(&__cs_local_loopexec_buf, mozillacmdline, temporary_filename, optional);
tloopexec_0_42:
IF(1,42,tloopexec_0_43)
                                        system(__cs_local_loopexec_buf);
                                        printf("invocation complete\n");
tloopexec_0_43:
IF(1,43,tloopexec_0_44)
                                        free((void *) __cs_local_loopexec_buf);
                                        __cs_local_loopexec_last_display = __cs_local_loopexec_current_time;
                                                                }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 44);
                                                                ;
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 44);
                                                        ;
tloopexec_0_44:
IF(1,44,tloopexec_0_45)
                                        __cs_mutex_unlock(&plock, 1);
                                                }
                                        ;
tloopexec_0_45:
IF(1,45,tloopexec_0_46)
                                        __CPROVER_assume(!((_Bool) 1));
                                        __exit_loop_1:
                                                __CPROVER_assume(__cs_pc_cs[1] >= 46);
                                        ;
                                                ;
                                        __exit_loopexec:
                                                __CPROVER_assume(__cs_pc_cs[1] >= 46);
                                        ;
                                                ;
tloopexec_0_46: 
                                        __cs_exit(0, 1);
                                        }
                                        signed int main_thread(void)
                                        {
                                                signed int __cs_param_main_ac;
                                                char **__cs_param_main_av;
IF(0,0,tmain_1)
                                        static unsigned long int __cs_local_main_t;
                                        __cs_init_scalar(&__cs_local_main_t, sizeof(unsigned long int));
                                        static signed int __cs_local_main_opt;
                                        ;
                                                ;
                                        static int __cs_local_main___cs_dowhile_onetime_1;
                                        __cs_local_main___cs_dowhile_onetime_1 = 0;
                                                {
                                        __cs_local_main_opt = getopt(__cs_param_main_ac, __cs_param_main_av, "m:s:x:");
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_6;
                                        __cs_local_main___cs_tmp_if_cond_6 = __cs_local_main_opt == (-1);
                                        if (__cs_local_main___cs_tmp_if_cond_6)
                                                        {
                                        goto __exit_loop_2;
                                                                ;
                                                        }
                                        ;
                                        ;
                                                        ;
                                        static int __cs_local_main___cs_switch_cond_main_1;
                                        __cs_local_main___cs_switch_cond_main_1 = __cs_local_main_opt;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_7;
                                        __cs_local_main___cs_tmp_if_cond_7 = __cs_local_main___cs_switch_cond_main_1 == 109;
                                        if (__cs_local_main___cs_tmp_if_cond_7)
                                                        {
                                                                {
                                        mozillacmdline = strdup(optarg);
                                        goto __cs_switch_main_1_exit_0;
                                                                        ;
                                                                }
                                        ;
                                        goto __cs_switch_main_1_case_2_0;
                                                                ;
                                                        }
                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_8;
                                        __cs_local_main___cs_tmp_if_cond_8 = __cs_local_main___cs_switch_cond_main_1 == 115;
                                        if (__cs_local_main___cs_tmp_if_cond_8)
                                                        {
                                        __cs_switch_main_1_case_2_0:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                                ;
                                                                {
                                        wait_sleeptime = atoi(optarg);
                                        goto __cs_switch_main_1_exit_0;
                                                                        ;
                                                                }
                                        ;
                                        goto __cs_switch_main_1_case_3_0;
                                                                ;
                                                        }
                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_9;
                                        __cs_local_main___cs_tmp_if_cond_9 = __cs_local_main___cs_switch_cond_main_1 == 120;
                                        if (__cs_local_main___cs_tmp_if_cond_9)
                                                        {
                                        __cs_switch_main_1_case_3_0:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                                ;
                                                                {
                                        xsltstylesheet = strdup(optarg);
                                        goto __cs_switch_main_1_exit_0;
                                                                        ;
                                                                }
                                        ;
                                        goto __cs_switch_main_1_case_4_0;
                                                                ;
                                                        }
                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_10;
                                        __cs_local_main___cs_tmp_if_cond_10 = !(((__cs_local_main___cs_switch_cond_main_1 == 109) || (__cs_local_main___cs_switch_cond_main_1 == 115)) || (__cs_local_main___cs_switch_cond_main_1 == 120));
                                        if (__cs_local_main___cs_tmp_if_cond_10)
                                                        {
                                        __cs_switch_main_1_case_4_0:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                                ;
                                                                {
                                        fprintf(stderr, "Unknown option -%c\n", __cs_local_main_opt);
                                        exit(1);
                                                                }
                                        ;
                                        goto __cs_switch_main_1_exit_0;
                                                                ;
                                                        }
                                        ;
                                        __cs_switch_main_1_exit_0:
                                                        __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                        ;
                                                }
                                        ;
                                        __cs_local_main___cs_dowhile_onetime_1++;
                                        __CPROVER_assume(!(__cs_local_main___cs_dowhile_onetime_1 < 1));
                                        __exit_loop_2:
                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                ;
                                        if (
                                        !((_Bool) 1))
                                                {
                                        goto __exit_loop_3;
                                                        ;
                                                }
                                        ;
                                                {
                                        __cs_local_main_opt = getopt(__cs_param_main_ac, __cs_param_main_av, "m:s:x:");
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_11;
                                        __cs_local_main___cs_tmp_if_cond_11 = __cs_local_main_opt == (-1);
                                        if (__cs_local_main___cs_tmp_if_cond_11)
                                                        {
                                        goto __exit_loop_3;
                                                                ;
                                                        }
                                        ;
                                        ;
                                                        ;
                                        static int __cs_local_main___cs_switch_cond_main_1;
                                        __cs_local_main___cs_switch_cond_main_1 = __cs_local_main_opt;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_12;
                                        __cs_local_main___cs_tmp_if_cond_12 = __cs_local_main___cs_switch_cond_main_1 == 109;
                                        if (__cs_local_main___cs_tmp_if_cond_12)
                                                        {
                                                                {
                                        mozillacmdline = strdup(optarg);
                                        goto __cs_switch_main_1_exit_1;
                                                                        ;
                                                                }
                                        ;
                                        goto __cs_switch_main_1_case_2_1;
                                                                ;
                                                        }
                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_13;
                                        __cs_local_main___cs_tmp_if_cond_13 = __cs_local_main___cs_switch_cond_main_1 == 115;
                                        if (__cs_local_main___cs_tmp_if_cond_13)
                                                        {
                                        __cs_switch_main_1_case_2_1:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                                ;
                                                                {
                                        wait_sleeptime = atoi(optarg);
                                        goto __cs_switch_main_1_exit_1;
                                                                        ;
                                                                }
                                        ;
                                        goto __cs_switch_main_1_case_3_1;
                                                                ;
                                                        }
                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_14;
                                        __cs_local_main___cs_tmp_if_cond_14 = __cs_local_main___cs_switch_cond_main_1 == 120;
                                        if (__cs_local_main___cs_tmp_if_cond_14)
                                                        {
                                        __cs_switch_main_1_case_3_1:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                                ;
                                                                {
                                        xsltstylesheet = strdup(optarg);
                                        goto __cs_switch_main_1_exit_1;
                                                                        ;
                                                                }
                                        ;
                                        goto __cs_switch_main_1_case_4_1;
                                                                ;
                                                        }
                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_15;
                                        __cs_local_main___cs_tmp_if_cond_15 = !(((__cs_local_main___cs_switch_cond_main_1 == 109) || (__cs_local_main___cs_switch_cond_main_1 == 115)) || (__cs_local_main___cs_switch_cond_main_1 == 120));
                                        if (__cs_local_main___cs_tmp_if_cond_15)
                                                        {
                                        __cs_switch_main_1_case_4_1:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                                ;
                                                                {
                                        fprintf(stderr, "Unknown option -%c\n", __cs_local_main_opt);
                                        exit(1);
                                                                }
                                        ;
                                        goto __cs_switch_main_1_exit_1;
                                                                ;
                                                        }
                                        ;
                                        __cs_switch_main_1_exit_1:
                                                        __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                        ;
                                                }
                                        ;
                                        if (
                                        !((_Bool) 1))
                                                {
                                        goto __exit_loop_3;
                                                        ;
                                                }
                                        ;
                                                {
                                        __cs_local_main_opt = getopt(__cs_param_main_ac, __cs_param_main_av, "m:s:x:");
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_11;
                                        __cs_local_main___cs_tmp_if_cond_11 = __cs_local_main_opt == (-1);
                                        if (__cs_local_main___cs_tmp_if_cond_11)
                                                        {
                                        goto __exit_loop_3;
                                                                ;
                                                        }
                                        ;
                                        ;
                                                        ;
                                        static int __cs_local_main___cs_switch_cond_main_1;
                                        __cs_local_main___cs_switch_cond_main_1 = __cs_local_main_opt;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_12;
                                        __cs_local_main___cs_tmp_if_cond_12 = __cs_local_main___cs_switch_cond_main_1 == 109;
                                        if (__cs_local_main___cs_tmp_if_cond_12)
                                                        {
                                                                {
                                        mozillacmdline = strdup(optarg);
                                        goto __cs_switch_main_1_exit_2;
                                                                        ;
                                                                }
                                        ;
                                        goto __cs_switch_main_1_case_2_2;
                                                                ;
                                                        }
                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_13;
                                        __cs_local_main___cs_tmp_if_cond_13 = __cs_local_main___cs_switch_cond_main_1 == 115;
                                        if (__cs_local_main___cs_tmp_if_cond_13)
                                                        {
                                        __cs_switch_main_1_case_2_2:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                                ;
                                                                {
                                        wait_sleeptime = atoi(optarg);
                                        goto __cs_switch_main_1_exit_2;
                                                                        ;
                                                                }
                                        ;
                                        goto __cs_switch_main_1_case_3_2;
                                                                ;
                                                        }
                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_14;
                                        __cs_local_main___cs_tmp_if_cond_14 = __cs_local_main___cs_switch_cond_main_1 == 120;
                                        if (__cs_local_main___cs_tmp_if_cond_14)
                                                        {
                                        __cs_switch_main_1_case_3_2:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                                ;
                                                                {
                                        xsltstylesheet = strdup(optarg);
                                        goto __cs_switch_main_1_exit_2;
                                                                        ;
                                                                }
                                        ;
                                        goto __cs_switch_main_1_case_4_2;
                                                                ;
                                                        }
                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_15;
                                        __cs_local_main___cs_tmp_if_cond_15 = !(((__cs_local_main___cs_switch_cond_main_1 == 109) || (__cs_local_main___cs_switch_cond_main_1 == 115)) || (__cs_local_main___cs_switch_cond_main_1 == 120));
                                        if (__cs_local_main___cs_tmp_if_cond_15)
                                                        {
                                        __cs_switch_main_1_case_4_2:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                                ;
                                                                {
                                        fprintf(stderr, "Unknown option -%c\n", __cs_local_main_opt);
                                        exit(1);
                                                                }
                                        ;
                                        goto __cs_switch_main_1_exit_2;
                                                                ;
                                                        }
                                        ;
                                        __cs_switch_main_1_exit_2:
                                                        __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                        ;
                                                }
                                        ;
                                        __CPROVER_assume(
                                        !((_Bool) 1));
                                        __exit_loop_3:
                                                __CPROVER_assume(__cs_pc_cs[0] >= 1);
                                        ;
                                                ;
                                        printf("wysidocbookdaemon Version %s, with wait %i seconds\n", (const void *) "0.13", wait_sleeptime);
                                        ;
                                                ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_16;
                                        __cs_local_main___cs_tmp_if_cond_16 = mozillacmdline == ((const char *) 0);
                                        if (__cs_local_main___cs_tmp_if_cond_16)
                                                {
                                        fprintf(stderr, "Mozilla command-line not specified\n");
                                        exit(1);
                                                }
                                        ;
                                        __cs_create(&__cs_local_main_t, (const union pthread_attr_t *) 0, loopexec_0, 0, 1);
                                        if (!((_Bool) 1))
                                                {
                                        goto __exit_loop_4;
                                                        ;
                                                }
                                        ;
                                                {
                                        static char *__cs_local_main_instr;
tmain_1:
IF(0,1,tmain_2)
                                        __cs_local_main_instr = (char *) 0;
                                        static char *__cs_local_main_my_optional;
tmain_2:
IF(0,2,tmain_3)
                                        __cs_local_main_my_optional = (char *) 0;
                                        printf(">");
tmain_3:
IF(0,3,tmain_4)
                                        scanf("%as %as", &__cs_local_main_instr, &__cs_local_main_my_optional);
tmain_4:
IF(0,4,tmain_5)
                                        __cs_mutex_lock(&plock, 0);
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_17;
tmain_5:
IF(0,5,tmain_6)
                                        if (((5 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&currentfile, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_main___cs_tmp_if_cond_17 = !(currentfile == ((char *) 0));
                                        if (__cs_local_main___cs_tmp_if_cond_17)
                                                        {
tmain_6:
IF(0,6,tmain_7)
                                        if (((6 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&currentfile, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        free((void *) currentfile);
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[0] >= 7);
                                                        ;
tmain_7:
                                        if (((7 == __cs_pc_cs[0]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                        {
                                        __CPROVER_set_field(&currentfile, "dr_write", 1);
                                                        }
IF(0,7,tmain_8)
                                        if (((7 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&currentfile, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        currentfile = __cs_local_main_instr;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_18;
tmain_8:
IF(0,8,tmain_9)
                                        if (((8 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&optional, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_main___cs_tmp_if_cond_18 = !(optional == ((char *) 0));
                                        if (__cs_local_main___cs_tmp_if_cond_18)
                                                        {
tmain_9:
IF(0,9,tmain_10)
                                        if (((9 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&optional, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        free((void *) optional);
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[0] >= 10);
                                                        ;
tmain_10:
                                        if (((10 == __cs_pc_cs[0]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                        {
                                        __CPROVER_set_field(&optional, "dr_write", 1);
                                                        }
IF(0,10,tmain_11)
                                        if (((10 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&optional, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        optional = __cs_local_main_my_optional;
tmain_11:
                                        if (((11 == __cs_pc_cs[0]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                        {
                                        __CPROVER_set_field(&last_input, "dr_write", 1);
                                                        }
IF(0,11,tmain_12)
                                        if (((11 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&last_input, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        last_input = time((signed long int *) 0);
tmain_12:
IF(0,12,tmain_13)
                                        __cs_mutex_unlock(&plock, 0);
                                                }
                                        ;
                                        if (!((_Bool) 1))
                                                {
                                        goto __exit_loop_4;
                                                        ;
                                                }
                                        ;
                                                {
                                        static char *__cs_local_main_instr;
tmain_13:
IF(0,13,tmain_14)
                                        __cs_local_main_instr = (char *) 0;
                                        static char *__cs_local_main_my_optional;
tmain_14:
IF(0,14,tmain_15)
                                        __cs_local_main_my_optional = (char *) 0;
                                        printf(">");
tmain_15:
IF(0,15,tmain_16)
                                        scanf("%as %as", &__cs_local_main_instr, &__cs_local_main_my_optional);
tmain_16:
IF(0,16,tmain_17)
                                        __cs_mutex_lock(&plock, 0);
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_17;
tmain_17:
IF(0,17,tmain_18)
                                        if (((17 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&currentfile, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_main___cs_tmp_if_cond_17 = !(currentfile == ((char *) 0));
                                        if (__cs_local_main___cs_tmp_if_cond_17)
                                                        {
tmain_18:
IF(0,18,tmain_19)
                                        if (((18 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&currentfile, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        free((void *) currentfile);
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[0] >= 19);
                                                        ;
tmain_19:
                                        if (((19 == __cs_pc_cs[0]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                        {
                                        __CPROVER_set_field(&currentfile, "dr_write", 1);
                                                        }
IF(0,19,tmain_20)
                                        if (((19 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&currentfile, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        currentfile = __cs_local_main_instr;
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_18;
tmain_20:
IF(0,20,tmain_21)
                                        if (((20 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&optional, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_main___cs_tmp_if_cond_18 = !(optional == ((char *) 0));
                                        if (__cs_local_main___cs_tmp_if_cond_18)
                                                        {
tmain_21:
IF(0,21,tmain_22)
                                        if (((21 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&optional, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        free((void *) optional);
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[0] >= 22);
                                                        ;
tmain_22:
                                        if (((22 == __cs_pc_cs[0]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                        {
                                        __CPROVER_set_field(&optional, "dr_write", 1);
                                                        }
IF(0,22,tmain_23)
                                        if (((22 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&optional, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        optional = __cs_local_main_my_optional;
tmain_23:
                                        if (((23 == __cs_pc_cs[0]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                        {
                                        __CPROVER_set_field(&last_input, "dr_write", 1);
                                                        }
IF(0,23,tmain_24)
                                        if (((23 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&last_input, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        last_input = time((signed long int *) 0);
tmain_24:
IF(0,24,tmain_25)
                                        __cs_mutex_unlock(&plock, 0);
                                                }
                                        ;
tmain_25:
IF(0,25,tmain_26)
                                        __CPROVER_assume(!((_Bool) 1));
                                        __exit_loop_4:
                                                __CPROVER_assume(__cs_pc_cs[0] >= 26);
                                        ;
                                                ;
                                        __exit_main:
                                                __CPROVER_assume(__cs_pc_cs[0] >= 26);
                                        ;
                                                ;
tmain_26: 
                                        __cs_exit(0, 0);
                                        }
                                        int main(void)
                                        {
                                        __CPROVER_field_decl_global("dr_write", (_Bool) 0);
                                        unsigned __CPROVER_bitvector[2] __cs_dr_ts;
                                        __CPROVER_assume(__cs_dr_ts <= 3);
/* round  0 */
/* main */
                                        unsigned __CPROVER_bitvector[5] __cs_tmp_t0_r0;
                                        __cs_pc_cs[0] = __cs_tmp_t0_r0;
                                        __CPROVER_assume(__cs_pc_cs[0] > 0);
                                        __CPROVER_assume(__cs_pc_cs[0] <= 26);
                                        if (__cs_dr_ts == 0)
                                                        __cs_dataraceDetectionStarted = 1;
                                        main_thread();
                                        if (__cs_dataraceDetectionStarted)
                                                        __cs_dataraceSecondThread = 1;
                                        __cs_pc[0] = __cs_pc_cs[0];
/* loopexec_0 */
                                        unsigned __CPROVER_bitvector[6] __cs_tmp_t1_r0;
                                        if (__cs_dataraceContinue & __cs_active_thread[1])
                                                {
                                        __cs_pc_cs[1] = __cs_tmp_t1_r0;
                                        __CPROVER_assume(__cs_pc_cs[1] <= 46);
                                        if (__cs_dr_ts == 1)
                                                                __cs_dataraceDetectionStarted = 1;
                                        loopexec_0(__cs_threadargs[1]);
                                        if (__cs_dataraceSecondThread & (__cs_tmp_t1_r0 > __cs_pc[1]))
                                                                __cs_dataraceContinue = 0;
                                        if (__cs_dataraceDetectionStarted)
                                                                __cs_dataraceSecondThread = 1;
                                        __cs_pc[1] = __cs_pc_cs[1];
                                                }
/* round  1 */
/* main */
                                        unsigned __CPROVER_bitvector[5] __cs_tmp_t0_r1;
                                        if (((__cs_dr_ts > 0) & __cs_dataraceContinue) & __cs_active_thread[0])
                                                {
                                        __cs_pc_cs[0] = __cs_pc[0] + __cs_tmp_t0_r1;
                                        __CPROVER_assume(__cs_pc_cs[0] >= __cs_pc[0]);
                                        __CPROVER_assume(__cs_pc_cs[0] <= 26);
                                        if (__cs_dr_ts == 2)
                                                                __cs_dataraceDetectionStarted = 1;
                                        main_thread();
                                        if (__cs_dataraceSecondThread & (__cs_tmp_t0_r1 > __cs_pc[0]))
                                                                __cs_dataraceContinue = 0;
                                        if (__cs_dataraceDetectionStarted)
                                                                __cs_dataraceSecondThread = 1;
                                        __cs_pc[0] = __cs_pc_cs[0];
                                                }
/* loopexec_0 */
                                        unsigned __CPROVER_bitvector[6] __cs_tmp_t1_r1;
                                        if (((__cs_dr_ts > 1) & __cs_dataraceContinue) & __cs_active_thread[1])
                                                {
                                        __cs_pc_cs[1] = __cs_pc[1] + __cs_tmp_t1_r1;
                                        __CPROVER_assume(__cs_pc_cs[1] >= __cs_pc[1]);
                                        __CPROVER_assume(__cs_pc_cs[1] <= 46);
                                        if (__cs_dr_ts == 3)
                                                                __cs_dataraceDetectionStarted = 1;
                                        loopexec_0(__cs_threadargs[1]);
                                        if (__cs_dataraceSecondThread & (__cs_tmp_t1_r1 > __cs_pc[1]))
                                                                __cs_dataraceContinue = 0;
                                        if (__cs_dataraceDetectionStarted)
                                                                __cs_dataraceSecondThread = 1;
                                        __cs_pc[1] = __cs_pc_cs[1];
                                                }
                                        unsigned __CPROVER_bitvector[5] __cs_tmp_t0_r2;
                                        if (((__cs_dr_ts > 0) & __cs_dataraceContinue) & __cs_active_thread[0])
                                                {
                                        __cs_pc_cs[0] = __cs_pc[0] + __cs_tmp_t0_r2;
                                        __CPROVER_assume(__cs_pc_cs[0] >= __cs_pc[0]);
                                        __CPROVER_assume(__cs_pc_cs[0] <= 26);
                                        main_thread();
                                                }
                                        __CPROVER_assert(__cs_dataraceNotDetected, "Data race failure");
                                        return 0;
                                        }
                                        
