/*
 *  generated by CSeq [ 0000 / 0000 ]
 * 
 *  instance version    {}
 *
 *  2019-04-30 10:33:21
 *
 *  params:
 *    -l datarace, -i ../DR-Experiments/truc/g15core.c, --rounds 2, --unwind 2, --debug , 
 *
 */
#define __cs_MUTEX_INITIALIZER -1
#define __cs_COND_INITIALIZER -1
#define __cs_RWLOCK_INITIALIZER -1
#define __cs_BARRIER_SERIAL_THREAD 0
#define __cs_CANCEL_ASYNCHRONOUS 0
#define __cs_CANCEL_ENABLE 0
#define __cs_CANCEL_DEFERRED 0
#define __cs_CANCEL_DISABLE 0
#define __cs_CANCELED 0
#define __cs_CREATE_DETACHED 0
#define __cs_CREATE_JOINABLE 0
#define __cs_EXPLICIT_SCHED 0
#define __cs_INHERIT_SCHED 0
#define __cs_MUTEX_DEFAULT 0
#define __cs_MUTEX_ERRORCHECK 0
#define __cs_MUTEX_NORMAL 0
#define __cs_MUTEX_RECURSIVE 0
#define __cs_MUTEX_ROBUST 0
#define __cs_MUTEX_STALLED 0
#define __cs_ONCE_INIT 0
#define __cs_PRIO_INHERIT 0
#define __cs_PRIO_NONE 0
#define __cs_PRIO_PROTECT 0
#define __cs_PROCESS_SHARED 0
#define __cs_PROCESS_PRIVATE 0
#define __cs_SCOPE_PROCESS 0
#define __cs_SCOPE_SYSTEM 0
#include <assert.h>
void *malloc(unsigned long int);
int __VERIFIER_nondet_int();
int nondet_int();
unsigned int __VERIFIER_nondet_uint();
unsigned int nondet_uint();
_Bool __VERIFIER_nondet_bool();
_Bool nondet_bool();
char __VERIFIER_nondet_char();
char nondet_char();
unsigned char __VERIFIER_nondet_uchar();
unsigned char nondet_uchar();
#define THREADS 3
#define ROUNDS 2
#define STOP_VOID(A) return;
#define STOP_NONVOID(A) return 0;
#define IF(T,A,B) if ((__cs_pc[T] > A) | (A >= __cs_pc_cs[T])) goto B; 

                                        unsigned __CPROVER_bitvector[1] __cs_active_thread[4] = {1};
                                        unsigned __CPROVER_bitvector[6] __cs_pc[4];
                                        unsigned __CPROVER_bitvector[7] __cs_pc_cs[4];
                                        unsigned __CPROVER_bitvector[2] __cs_last_thread;
                                        unsigned __CPROVER_bitvector[6] __cs_thread_lines[4] = {43, 12, 10, 4};
                                        void *__cs_safe_malloc(unsigned int __cs_size)
                                        {
                                        void *__cs_ptr = (malloc(__cs_size));
                                        return __cs_ptr;
                                        }
                                        void __cs_init_scalar(void *__cs_var, unsigned int __cs_size)
                                        {
                                        if (__cs_size == (sizeof(int)))
                                        *((int *) __cs_var) = nondet_int();
                                                else
                                                {
                                        __cs_var = malloc(__cs_size);
                                                }
                                        }
                                        void __CSEQ_message(char *__cs_message)
                                        {
                                                ;
                                        }
                                        typedef int __cs_t;
                                        void *__cs_threadargs[4];
                                        void *__cs_thread_joinargs[4];
                                        int __cs_create(__cs_t *__cs_new_thread_id, void *__cs_attr, void *(*__cs_thread_function)(void *), void *__cs_arg, int __cs_threadID)
                                        {
                                        if (__cs_threadID > THREADS)
                                                        return 0;
                                        *__cs_new_thread_id = __cs_threadID;
                                        __cs_active_thread[__cs_threadID] = 1;
                                        __cs_threadargs[__cs_threadID] = __cs_arg;
                                        __CSEQ_message("thread spawned");
                                        return 0;
                                        }
                                        int __cs_join(__cs_t __cs_id, void **__cs_value_ptr)
                                        {
                                        __CPROVER_assume(__cs_pc[__cs_id] == __cs_thread_lines[__cs_id]);
                                        *__cs_value_ptr = __cs_thread_joinargs[__cs_id];
                                        return 0;
                                        }
                                        int __cs_exit(void *__cs_value_ptr, unsigned int __cs_thread_index)
                                        {
                                        __cs_thread_joinargs[__cs_thread_index] = __cs_value_ptr;
                                        return 0;
                                        }
                                        int __cs_self(void)
                                        {
                                                return 1;
                                        }
                                        typedef int __cs_mutex_t;
                                        int __cs_mutex_init(__cs_mutex_t *__cs_m, int __cs_val)
                                        {
                                        *__cs_m = -1;
                                        return 0;
                                        }
                                        int __cs_mutex_destroy(__cs_mutex_t *__cs_mutex_to_destroy)
                                        {
                                        __CPROVER_assume((*__cs_mutex_to_destroy) != 0);
                                        __CPROVER_assume((*__cs_mutex_to_destroy) != (-2));
                                        __CPROVER_assume((*__cs_mutex_to_destroy) == (-1));
                                        *__cs_mutex_to_destroy = -2;
                                        __CSEQ_message("lock destroyed");
                                        return 0;
                                        }
                                        int __cs_mutex_lock(__cs_mutex_t *__cs_mutex_to_lock, unsigned __CPROVER_bitvector[2] __cs_thread_index)
                                        {
                                        __CPROVER_assume((*__cs_mutex_to_lock) != 0);
                                        __CPROVER_assume((*__cs_mutex_to_lock) != (-2));
                                        __CPROVER_assume((*__cs_mutex_to_lock) == (-1));
                                        *__cs_mutex_to_lock = __cs_thread_index + 1;
                                        __CSEQ_message("lock acquired");
                                        return 0;
                                        }
                                        int __cs_mutex_unlock(__cs_mutex_t *__cs_mutex_to_unlock, unsigned __CPROVER_bitvector[2] __cs_thread_index)
                                        {
                                        __CPROVER_assume((*__cs_mutex_to_unlock) != 0);
                                        __CPROVER_assume((*__cs_mutex_to_unlock) != (-2));
                                        __CPROVER_assume((*__cs_mutex_to_unlock) == (__cs_thread_index + 1));
                                        *__cs_mutex_to_unlock = -1;
                                        __CSEQ_message("lock released");
                                        return 0;
                                        }
                                        typedef int __cs_cond_t;
                                        int __cs_cond_init(__cs_cond_t *__cs_cond_to_init, void *__cs_attr)
                                        {
                                        *__cs_cond_to_init = -1;
                                        return 0;
                                        }
                                        int __cs_cond_destroy(__cs_cond_t *__cs_cond_to_destroy)
                                        {
                                        *__cs_cond_to_destroy = -2;
                                        return 0;
                                        }
                                        int __cs_cond_wait_1(__cs_cond_t *__cs_cond_to_wait_for, __cs_mutex_t *__cs_m, unsigned int __cs_thread_index)
                                        {
                                        __CPROVER_assume((*__cs_cond_to_wait_for) != 0);
                                        __CPROVER_assume((*__cs_cond_to_wait_for) != (-2));
                                        __cs_mutex_unlock(__cs_m, __cs_thread_index);
                                        return 0;
                                        }
                                        int __cs_cond_wait_2(__cs_cond_t *__cs_cond_to_wait_for, __cs_mutex_t *__cs_m, unsigned int __cs_thread_index)
                                        {
                                        __CPROVER_assume((*__cs_cond_to_wait_for) == 1);
                                        __cs_mutex_lock(__cs_m, __cs_thread_index);
                                        return 0;
                                        }
                                        int __cs_cond_signal(__cs_cond_t *__cs_cond_to_signal)
                                        {
                                        *__cs_cond_to_signal = 1;
                                        __CSEQ_message("conditional variable signal");
                                        return 0;
                                        }
                                        int __cs_cond_broadcast(__cs_cond_t *__cs_cond_to_broadcast)
                                        {
                                        *__cs_cond_to_broadcast = 1;
                                        __CSEQ_message("conditional variable broadcast");
                                        return 0;
                                        }
                                        typedef struct __cs_barrier_t
                                        {
                                        unsigned int init;
                                        unsigned int current;
                                        } __cs_barrier_t;
                                        int __cs_barrier_init(__cs_barrier_t *__cs_barrier_to_init, void *__cs_attr, unsigned int count)
                                        {
                                        __CPROVER_assume(count > 0);
                                        __cs_barrier_to_init->current = count;
                                        __cs_barrier_to_init->init = count;
                                        return 0;
                                        }
                                        int __cs_barrier_destroy(__cs_barrier_t *__cs_barrier_to_destroy)
                                        {
                                        __cs_barrier_to_destroy->init = -1;
                                        __cs_barrier_to_destroy->current = -1;
                                        return 0;
                                        }
                                        int __cs_barrier_wait_1(__cs_barrier_t *__cs_barrier_to_wait)
                                        {
                                        __CPROVER_assume(__cs_barrier_to_wait->init > 0);
                                        __cs_barrier_to_wait->current--;
                                        return 0;
                                        }
                                        int __cs_barrier_wait_2(__cs_barrier_t *__cs_barrier_to_wait)
                                        {
                                        __CPROVER_assume(__cs_barrier_to_wait->init > 0);
                                        __CPROVER_assume(__cs_barrier_to_wait->current == 0);
                                        __cs_barrier_to_wait->current = __cs_barrier_to_wait->init;
                                        return 0;
                                        }
                                        typedef int __cs_attr_t;
                                        struct sched_param
                                        {
                                        int sched_priority;
                                        };
                                        int __cs_attr_init(__cs_attr_t *t)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_destroy(__cs_attr_t *t)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getdetachstate(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getguardsize(const __cs_attr_t *t, unsigned int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getinheritsched(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getschedparam(const __cs_attr_t *t, struct sched_param *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getschedpolicy(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getscope(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getstackaddr(const __cs_attr_t *t, void **s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getstacksize(const __cs_attr_t *t, unsigned int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setdetachstate(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setguardsize(__cs_attr_t *t, unsigned int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setinheritsched(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setschedparam(__cs_attr_t *t, const struct sched_param *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setschedpolicy(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setscope(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setstackaddr(__cs_attr_t *t, void *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setstacksize(__cs_attr_t *t, unsigned int s)
                                        {
                                                return 0;
                                        }
                                        _Bool __cs_dataraceDetectionStarted = (0);
                                        _Bool __cs_dataraceSecondThread = (0);
                                        _Bool __cs_dataraceNotDetected = (1);
                                        _Bool __cs_dataraceContinue = (1);
                                        signed int read();
                                        signed int leaving;
                                        signed int _volume;
                                        signed int volume_adjust;
                                        __cs_mutex_t daemon_mutex;
                                        void *Lkeys_thread_0(void *__cs_param_Lkeys_thread___cs_unused)
                                        {
                                        static signed int __cs_local_Lkeys_thread_keystate;
IF(1,0,tLkeys_thread_0_1)
                                        __cs_local_Lkeys_thread_keystate = 0;
tLkeys_thread_0_1:
IF(1,1,tLkeys_thread_0_2)
                                        if (!(leaving == 0))
                                                {
                                        goto __exit_loop_1;
                                                        ;
                                                }
                                        ;
                                                {
tLkeys_thread_0_2:
IF(1,2,tLkeys_thread_0_3)
                                        __cs_mutex_lock(&daemon_mutex, 1);
                                        __cs_local_Lkeys_thread_keystate = read();
                                        ;
                                                        ;
                                        static int __cs_local_Lkeys_thread___cs_switch_cond_Lkeys_thread_1;
                                        __cs_local_Lkeys_thread___cs_switch_cond_Lkeys_thread_1 = __cs_local_Lkeys_thread_keystate;
                                        ;
                                                        ;
                                        static _Bool __cs_local_Lkeys_thread___cs_tmp_if_cond_0;
                                        __cs_local_Lkeys_thread___cs_tmp_if_cond_0 = __cs_local_Lkeys_thread___cs_switch_cond_Lkeys_thread_1 == 33554432;
                                        if (__cs_local_Lkeys_thread___cs_tmp_if_cond_0)
                                                        {
                                                                {
                                        static signed int __cs_local_Lkeys_thread_volume;
                                        static signed int __cs_retval__mpd_status_get_volume_1;
                                                                        {
tLkeys_thread_0_3:
IF(1,3,tLkeys_thread_0_4)
                                        if (((3 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&_volume, "dr_write"))
                                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_retval__mpd_status_get_volume_1 = _volume;
                                        goto __exit__mpd_status_get_volume_1_0;
                                                                                ;
                                        __exit__mpd_status_get_volume_1_0:
                                                                                __CPROVER_assume(__cs_pc_cs[1] >= 4);
                                        ;
                                                                                ;
                                                                        }
                                        ;
                                        __cs_local_Lkeys_thread_volume = __cs_retval__mpd_status_get_volume_1;
                                        ;
                                                                        ;
                                        static _Bool __cs_local_Lkeys_thread___cs_tmp_if_cond_1;
                                        __cs_local_Lkeys_thread___cs_tmp_if_cond_1 = __cs_local_Lkeys_thread_volume >= 1;
                                        if (__cs_local_Lkeys_thread___cs_tmp_if_cond_1)
                                                                        {
                                        __cs_local_Lkeys_thread_volume = __cs_local_Lkeys_thread_volume - 1;
                                                                        }
                                        ;
                                                                        {
                                        static signed int __cs_param_mpd_status_set_volume_volume;
                                        __cs_param_mpd_status_set_volume_volume = __cs_local_Lkeys_thread_volume;
tLkeys_thread_0_4:
                                        if (((4 == __cs_pc_cs[1]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                                                {
                                        __CPROVER_set_field(&_volume, "dr_write", 1);
                                                                                }
IF(1,4,tLkeys_thread_0_5)
                                        if (((4 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&_volume, "dr_write"))
                                                                                        __cs_dataraceNotDetected = 0;
                                        _volume = __cs_param_mpd_status_set_volume_volume;
                                        __exit__mpd_status_set_volume_1_0:
                                                                                __CPROVER_assume(__cs_pc_cs[1] >= 5);
                                        ;
                                                                                ;
                                                                        }
                                        ;
                                        goto __cs_switch_Lkeys_thread_1_exit_Lkeys_thread_0_0;
                                                                        ;
                                                                }
                                        ;
                                        goto __cs_switch_Lkeys_thread_1_case_2_Lkeys_thread_0_0;
                                                                ;
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 5);
                                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_Lkeys_thread___cs_tmp_if_cond_2;
                                        __cs_local_Lkeys_thread___cs_tmp_if_cond_2 = !(__cs_local_Lkeys_thread___cs_switch_cond_Lkeys_thread_1 == 33554432);
                                        if (__cs_local_Lkeys_thread___cs_tmp_if_cond_2)
                                                        {
                                        __cs_switch_Lkeys_thread_1_case_2_Lkeys_thread_0_0:
                                                                __CPROVER_assume(__cs_pc_cs[1] >= 5);
                                        ;
                                                                ;
                                        goto __cs_switch_Lkeys_thread_1_exit_Lkeys_thread_0_0;
                                                                ;
                                                        }
                                        ;
                                        __cs_switch_Lkeys_thread_1_exit_Lkeys_thread_0_0:
                                                        __CPROVER_assume(__cs_pc_cs[1] >= 5);
                                        ;
                                                        ;
tLkeys_thread_0_5:
IF(1,5,tLkeys_thread_0_6)
                                        __cs_mutex_unlock(&daemon_mutex, 1);
                                                }
                                        ;
tLkeys_thread_0_6:
IF(1,6,tLkeys_thread_0_7)
                                        if (!(leaving == 0))
                                                {
                                        goto __exit_loop_1;
                                                        ;
                                                }
                                        ;
                                                {
tLkeys_thread_0_7:
IF(1,7,tLkeys_thread_0_8)
                                        __cs_mutex_lock(&daemon_mutex, 1);
                                        __cs_local_Lkeys_thread_keystate = read();
                                        ;
                                                        ;
                                        static int __cs_local_Lkeys_thread___cs_switch_cond_Lkeys_thread_1;
                                        __cs_local_Lkeys_thread___cs_switch_cond_Lkeys_thread_1 = __cs_local_Lkeys_thread_keystate;
                                        ;
                                                        ;
                                        static _Bool __cs_local_Lkeys_thread___cs_tmp_if_cond_0;
                                        __cs_local_Lkeys_thread___cs_tmp_if_cond_0 = __cs_local_Lkeys_thread___cs_switch_cond_Lkeys_thread_1 == 33554432;
                                        if (__cs_local_Lkeys_thread___cs_tmp_if_cond_0)
                                                        {
                                                                {
                                        static signed int __cs_local_Lkeys_thread_volume;
                                        static signed int __cs_retval__mpd_status_get_volume_1;
                                                                        {
tLkeys_thread_0_8:
IF(1,8,tLkeys_thread_0_9)
                                        if (((8 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&_volume, "dr_write"))
                                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_retval__mpd_status_get_volume_1 = _volume;
                                        goto __exit__mpd_status_get_volume_1_1;
                                                                                ;
                                        __exit__mpd_status_get_volume_1_1:
                                                                                __CPROVER_assume(__cs_pc_cs[1] >= 9);
                                        ;
                                                                                ;
                                                                        }
                                        ;
                                        __cs_local_Lkeys_thread_volume = __cs_retval__mpd_status_get_volume_1;
                                        ;
                                                                        ;
                                        static _Bool __cs_local_Lkeys_thread___cs_tmp_if_cond_1;
                                        __cs_local_Lkeys_thread___cs_tmp_if_cond_1 = __cs_local_Lkeys_thread_volume >= 1;
                                        if (__cs_local_Lkeys_thread___cs_tmp_if_cond_1)
                                                                        {
                                        __cs_local_Lkeys_thread_volume = __cs_local_Lkeys_thread_volume - 1;
                                                                        }
                                        ;
                                                                        {
                                        static signed int __cs_param_mpd_status_set_volume_volume;
                                        __cs_param_mpd_status_set_volume_volume = __cs_local_Lkeys_thread_volume;
tLkeys_thread_0_9:
                                        if (((9 == __cs_pc_cs[1]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                                                {
                                        __CPROVER_set_field(&_volume, "dr_write", 1);
                                                                                }
IF(1,9,tLkeys_thread_0_10)
                                        if (((9 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&_volume, "dr_write"))
                                                                                        __cs_dataraceNotDetected = 0;
                                        _volume = __cs_param_mpd_status_set_volume_volume;
                                        __exit__mpd_status_set_volume_1_1:
                                                                                __CPROVER_assume(__cs_pc_cs[1] >= 10);
                                        ;
                                                                                ;
                                                                        }
                                        ;
                                        goto __cs_switch_Lkeys_thread_1_exit_Lkeys_thread_0_1;
                                                                        ;
                                                                }
                                        ;
                                        goto __cs_switch_Lkeys_thread_1_case_2_Lkeys_thread_0_1;
                                                                ;
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[1] >= 10);
                                                        ;
                                        ;
                                                        ;
                                        static _Bool __cs_local_Lkeys_thread___cs_tmp_if_cond_2;
                                        __cs_local_Lkeys_thread___cs_tmp_if_cond_2 = !(__cs_local_Lkeys_thread___cs_switch_cond_Lkeys_thread_1 == 33554432);
                                        if (__cs_local_Lkeys_thread___cs_tmp_if_cond_2)
                                                        {
                                        __cs_switch_Lkeys_thread_1_case_2_Lkeys_thread_0_1:
                                                                __CPROVER_assume(__cs_pc_cs[1] >= 10);
                                        ;
                                                                ;
                                        goto __cs_switch_Lkeys_thread_1_exit_Lkeys_thread_0_1;
                                                                ;
                                                        }
                                        ;
                                        __cs_switch_Lkeys_thread_1_exit_Lkeys_thread_0_1:
                                                        __CPROVER_assume(__cs_pc_cs[1] >= 10);
                                        ;
                                                        ;
tLkeys_thread_0_10:
IF(1,10,tLkeys_thread_0_11)
                                        __cs_mutex_unlock(&daemon_mutex, 1);
                                                }
                                        ;
tLkeys_thread_0_11:
IF(1,11,tLkeys_thread_0_12)
                                        if (((11 == __cs_pc[1]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&leaving, "dr_write"))
                                                        __cs_dataraceNotDetected = 0;
                                        __CPROVER_assume(!(leaving == 0));
                                        __exit_loop_1:
                                                __CPROVER_assume(__cs_pc_cs[1] >= 12);
                                        ;
                                                ;
                                        goto __exit_Lkeys_thread;
                                                ;
                                        __exit_Lkeys_thread:
                                                __CPROVER_assume(__cs_pc_cs[1] >= 12);
                                        ;
                                                ;
tLkeys_thread_0_12: 
                                        __cs_exit(0, 1);
                                        }
                                        void *event_key_thread_0(void *__cs_param_event_key_thread___cs_unused)
                                        {
                                        static signed int __cs_local_event_key_thread_keycode;
IF(2,0,tevent_key_thread_0_1)
                                        __cs_local_event_key_thread_keycode = 0;
                                        static signed int __cs_local_event_key_thread_code_audio_lowervol;
                                        __cs_local_event_key_thread_code_audio_lowervol = 114;
tevent_key_thread_0_1:
IF(2,1,tevent_key_thread_0_2)
                                        if (!(leaving == 0))
                                                {
                                        goto __exit_loop_2;
                                                        ;
                                                }
                                        ;
                                                {
                                        __cs_local_event_key_thread_keycode = read();
                                        ;
                                                        ;
                                        static _Bool __cs_local_event_key_thread___cs_tmp_if_cond_3;
                                        __cs_local_event_key_thread___cs_tmp_if_cond_3 = __cs_local_event_key_thread_keycode == __cs_local_event_key_thread_code_audio_lowervol;
                                        if (__cs_local_event_key_thread___cs_tmp_if_cond_3)
                                                        {
tevent_key_thread_0_2:
IF(2,2,tevent_key_thread_0_3)
                                        __cs_mutex_lock(&daemon_mutex, 2);
tevent_key_thread_0_3:
                                        if (((3 == __cs_pc_cs[2]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                                {
                                        __CPROVER_set_field(&volume_adjust, "dr_write", 1);
                                                                }
IF(2,3,tevent_key_thread_0_4)
                                        if (((3 == __cs_pc[2]) & __cs_dataraceSecondThread) & (__CPROVER_get_field(&volume_adjust, "dr_write") || __CPROVER_get_field(&volume_adjust, "dr_write")))
                                                                        __cs_dataraceNotDetected = 0;
                                        volume_adjust = volume_adjust - 1;
tevent_key_thread_0_4:
IF(2,4,tevent_key_thread_0_5)
                                        __cs_mutex_unlock(&daemon_mutex, 2);
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[2] >= 5);
                                                        ;
                                                }
                                        ;
tevent_key_thread_0_5:
IF(2,5,tevent_key_thread_0_6)
                                        if (!(leaving == 0))
                                                {
                                        goto __exit_loop_2;
                                                        ;
                                                }
                                        ;
                                                {
                                        __cs_local_event_key_thread_keycode = read();
                                        ;
                                                        ;
                                        static _Bool __cs_local_event_key_thread___cs_tmp_if_cond_3;
                                        __cs_local_event_key_thread___cs_tmp_if_cond_3 = __cs_local_event_key_thread_keycode == __cs_local_event_key_thread_code_audio_lowervol;
                                        if (__cs_local_event_key_thread___cs_tmp_if_cond_3)
                                                        {
tevent_key_thread_0_6:
IF(2,6,tevent_key_thread_0_7)
                                        __cs_mutex_lock(&daemon_mutex, 2);
tevent_key_thread_0_7:
                                        if (((7 == __cs_pc_cs[2]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                                {
                                        __CPROVER_set_field(&volume_adjust, "dr_write", 1);
                                                                }
IF(2,7,tevent_key_thread_0_8)
                                        if (((7 == __cs_pc[2]) & __cs_dataraceSecondThread) & (__CPROVER_get_field(&volume_adjust, "dr_write") || __CPROVER_get_field(&volume_adjust, "dr_write")))
                                                                        __cs_dataraceNotDetected = 0;
                                        volume_adjust = volume_adjust - 1;
tevent_key_thread_0_8:
IF(2,8,tevent_key_thread_0_9)
                                        __cs_mutex_unlock(&daemon_mutex, 2);
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[2] >= 9);
                                                        ;
                                                }
                                        ;
tevent_key_thread_0_9:
IF(2,9,tevent_key_thread_0_10)
                                        if (((9 == __cs_pc[2]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&leaving, "dr_write"))
                                                        __cs_dataraceNotDetected = 0;
                                        __CPROVER_assume(!(leaving == 0));
                                        __exit_loop_2:
                                                __CPROVER_assume(__cs_pc_cs[2] >= 10);
                                        ;
                                                ;
                                        goto __exit_event_key_thread;
                                                ;
                                        __exit_event_key_thread:
                                                __CPROVER_assume(__cs_pc_cs[2] >= 10);
                                        ;
                                                ;
tevent_key_thread_0_10: 
                                        __cs_exit(0, 2);
                                        }
                                        void *g15display_thread_0(void *__cs_param_g15display_thread___cs_unused)
                                        {
IF(3,0,tg15display_thread_0_1)
                                        __cs_mutex_lock(&daemon_mutex, 3);
                                        static signed int __cs_local_g15display_thread_volume;
                                        static signed int __cs_retval__mpd_status_get_volume_2;
                                                {
tg15display_thread_0_1:
IF(3,1,tg15display_thread_0_2)
                                        if (((1 == __cs_pc[3]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&_volume, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        __cs_retval__mpd_status_get_volume_2 = _volume;
                                        goto __exit__mpd_status_get_volume_2;
                                                        ;
                                        __exit__mpd_status_get_volume_2:
                                                        __CPROVER_assume(__cs_pc_cs[3] >= 2);
                                        ;
                                                        ;
                                                }
                                        ;
                                        __cs_local_g15display_thread_volume = __cs_retval__mpd_status_get_volume_2;
tg15display_thread_0_2:
IF(3,2,tg15display_thread_0_3)
                                        __cs_mutex_unlock(&daemon_mutex, 3);
tg15display_thread_0_3:
IF(3,3,tg15display_thread_0_4)
                                        __CPROVER_assume(__cs_local_g15display_thread_volume >= 0);
                                        __exit_g15display_thread:
                                                __CPROVER_assume(__cs_pc_cs[3] >= 4);
                                        ;
                                                ;
tg15display_thread_0_4: 
                                        __cs_exit(0, 3);
                                        }
                                        signed int main_thread(void)
                                        {
                                                signed int __cs_param_main_argc;
                                                char **__cs_param_main_argv;
IF(0,0,tmain_1)
                                        static signed int __cs_local_main_init_volume;
                                        __cs_init_scalar(&__cs_local_main_init_volume, sizeof(signed int));
                                        __CPROVER_assume(__cs_local_main_init_volume >= 5);
                                        __CPROVER_assume(__cs_local_main_init_volume <= 10);
                                        _volume = __cs_local_main_init_volume;
                                        static signed int __cs_local_main_init_volume_adjust;
                                        __cs_init_scalar(&__cs_local_main_init_volume_adjust, sizeof(signed int));
                                        __CPROVER_assume((__cs_local_main_init_volume_adjust >= (-10)) && (__cs_local_main_init_volume_adjust <= 10));
                                        volume_adjust = __cs_local_main_init_volume_adjust;
                                        static unsigned long int __cs_local_main_Lkeys;
                                        __cs_init_scalar(&__cs_local_main_Lkeys, sizeof(unsigned long int));
                                        static unsigned long int __cs_local_main_g15display;
                                        __cs_init_scalar(&__cs_local_main_g15display, sizeof(unsigned long int));
                                        static unsigned long int __cs_local_main_EKeys;
                                        __cs_init_scalar(&__cs_local_main_EKeys, sizeof(unsigned long int));
                                        __cs_mutex_init(&daemon_mutex, 0);
                                        __cs_create(&__cs_local_main_Lkeys, 0, Lkeys_thread_0, 0, 1);
tmain_1:
IF(0,1,tmain_2)
                                        __cs_create(&__cs_local_main_EKeys, 0, event_key_thread_0, 0, 2);
tmain_2:
IF(0,2,tmain_3)
                                        __cs_create(&__cs_local_main_g15display, 0, g15display_thread_0, 0, 3);
                                        ;
                                                ;
                                        static int __cs_local_main___cs_dowhile_onetime_1;
                                        __cs_local_main___cs_dowhile_onetime_1 = 0;
                                                {
tmain_3:
IF(0,3,tmain_4)
                                        __cs_mutex_lock(&daemon_mutex, 0);
                                        static signed int __cs_local_main_volume;
                                        static signed int __cs_retval__mpd_status_get_volume_3;
                                                        {
tmain_4:
IF(0,4,tmain_5)
                                        if (((4 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&_volume, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_retval__mpd_status_get_volume_3 = _volume;
                                        goto __exit__mpd_status_get_volume_3_0;
                                                                ;
                                        __exit__mpd_status_get_volume_3_0:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 5);
                                        ;
                                                                ;
                                                        }
                                        ;
                                        __cs_local_main_volume = __cs_retval__mpd_status_get_volume_3;
                                        static signed int __cs_local_main_checked;
tmain_5:
IF(0,5,tmain_6)
                                        if (((5 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&volume_adjust, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_main_checked = (volume_adjust + __cs_local_main_volume) <= 0;
tmain_6:
IF(0,6,tmain_7)
                                        __cs_mutex_unlock(&daemon_mutex, 0);
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_4;
                                        __cs_local_main___cs_tmp_if_cond_4 = __cs_local_main_checked;
                                        if (__cs_local_main___cs_tmp_if_cond_4)
                                                        {
tmain_7:
IF(0,7,tmain_8)
                                        __cs_mutex_lock(&daemon_mutex, 0);
tmain_8:
                                        if (((8 == __cs_pc_cs[0]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                                {
                                        __CPROVER_set_field(&volume_adjust, "dr_write", 1);
                                                                }
IF(0,8,tmain_9)
                                        if (((8 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&volume_adjust, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        volume_adjust = 0;
tmain_9:
IF(0,9,tmain_10)
                                        __cs_mutex_unlock(&daemon_mutex, 0);
                                        __cs_local_main_volume = 1;
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[0] >= 10);
                                                        ;
                                        ;
                                                        ;
                                        static signed int __cs_local_main___cs_temporary_0;
                                        __cs_local_main___cs_temporary_0 = 0;
                                        __cs_local_main___cs_temporary_0 = __cs_local_main_volume;
tmain_10:
IF(0,10,tmain_11)
                                        if (((10 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&volume_adjust, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_main_volume = __cs_local_main___cs_temporary_0 + volume_adjust;
tmain_11:
IF(0,11,tmain_12)
                                        __cs_mutex_lock(&daemon_mutex, 0);
                                                        {
                                        static signed int __cs_param_mpd_status_set_volume_volume;
                                        __cs_param_mpd_status_set_volume_volume = __cs_local_main_volume;
tmain_12:
                                        if (((12 == __cs_pc_cs[0]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                                {
                                        __CPROVER_set_field(&_volume, "dr_write", 1);
                                                                }
IF(0,12,tmain_13)
                                        if (((12 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&_volume, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        _volume = __cs_param_mpd_status_set_volume_volume;
                                        __exit__mpd_status_set_volume_2_0:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 13);
                                        ;
                                                                ;
                                                        }
                                        ;
tmain_13:
IF(0,13,tmain_14)
                                        __cs_mutex_unlock(&daemon_mutex, 0);
                                                }
                                        ;
                                        __cs_local_main___cs_dowhile_onetime_1++;
tmain_14:
IF(0,14,tmain_15)
                                        __CPROVER_assume(!(__cs_local_main___cs_dowhile_onetime_1 < 1));
                                        __exit_loop_3:
                                                __CPROVER_assume(__cs_pc_cs[0] >= 15);
                                        ;
                                                ;
tmain_15:
IF(0,15,tmain_16)
                                        if (
                                        !(leaving == 0))
                                                {
                                        goto __exit_loop_4;
                                                        ;
                                                }
                                        ;
                                                {
tmain_16:
IF(0,16,tmain_17)
                                        __cs_mutex_lock(&daemon_mutex, 0);
                                        static signed int __cs_local_main_volume;
                                        static signed int __cs_retval__mpd_status_get_volume_4;
                                                        {
tmain_17:
IF(0,17,tmain_18)
                                        if (((17 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&_volume, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_retval__mpd_status_get_volume_4 = _volume;
                                        goto __exit__mpd_status_get_volume_4_0;
                                                                ;
                                        __exit__mpd_status_get_volume_4_0:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 18);
                                        ;
                                                                ;
                                                        }
                                        ;
                                        __cs_local_main_volume = __cs_retval__mpd_status_get_volume_4;
                                        static signed int __cs_local_main_checked;
tmain_18:
IF(0,18,tmain_19)
                                        if (((18 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&volume_adjust, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_main_checked = (volume_adjust + __cs_local_main_volume) <= 0;
tmain_19:
IF(0,19,tmain_20)
                                        __cs_mutex_unlock(&daemon_mutex, 0);
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_5;
                                        __cs_local_main___cs_tmp_if_cond_5 = __cs_local_main_checked;
                                        if (__cs_local_main___cs_tmp_if_cond_5)
                                                        {
tmain_20:
IF(0,20,tmain_21)
                                        __cs_mutex_lock(&daemon_mutex, 0);
tmain_21:
                                        if (((21 == __cs_pc_cs[0]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                                {
                                        __CPROVER_set_field(&volume_adjust, "dr_write", 1);
                                                                }
IF(0,21,tmain_22)
                                        if (((21 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&volume_adjust, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        volume_adjust = 0;
tmain_22:
IF(0,22,tmain_23)
                                        __cs_mutex_unlock(&daemon_mutex, 0);
                                        __cs_local_main_volume = 1;
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[0] >= 23);
                                                        ;
                                        ;
                                                        ;
                                        static signed int __cs_local_main___cs_temporary_0;
                                        __cs_local_main___cs_temporary_0 = 0;
                                        __cs_local_main___cs_temporary_0 = __cs_local_main_volume;
tmain_23:
IF(0,23,tmain_24)
                                        if (((23 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&volume_adjust, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_main_volume = __cs_local_main___cs_temporary_0 + volume_adjust;
tmain_24:
IF(0,24,tmain_25)
                                        __cs_mutex_lock(&daemon_mutex, 0);
                                                        {
                                        static signed int __cs_param_mpd_status_set_volume_volume;
                                        __cs_param_mpd_status_set_volume_volume = __cs_local_main_volume;
tmain_25:
                                        if (((25 == __cs_pc_cs[0]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                                {
                                        __CPROVER_set_field(&_volume, "dr_write", 1);
                                                                }
IF(0,25,tmain_26)
                                        if (((25 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&_volume, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        _volume = __cs_param_mpd_status_set_volume_volume;
                                        __exit__mpd_status_set_volume_3_0:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 26);
                                        ;
                                                                ;
                                                        }
                                        ;
tmain_26:
IF(0,26,tmain_27)
                                        __cs_mutex_unlock(&daemon_mutex, 0);
                                                }
                                        ;
tmain_27:
IF(0,27,tmain_28)
                                        if (
                                        !(leaving == 0))
                                                {
                                        goto __exit_loop_4;
                                                        ;
                                                }
                                        ;
                                                {
tmain_28:
IF(0,28,tmain_29)
                                        __cs_mutex_lock(&daemon_mutex, 0);
                                        static signed int __cs_local_main_volume;
                                        static signed int __cs_retval__mpd_status_get_volume_4;
                                                        {
tmain_29:
IF(0,29,tmain_30)
                                        if (((29 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&_volume, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        __cs_retval__mpd_status_get_volume_4 = _volume;
                                        goto __exit__mpd_status_get_volume_4_1;
                                                                ;
                                        __exit__mpd_status_get_volume_4_1:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 30);
                                        ;
                                                                ;
                                                        }
                                        ;
                                        __cs_local_main_volume = __cs_retval__mpd_status_get_volume_4;
                                        static signed int __cs_local_main_checked;
tmain_30:
IF(0,30,tmain_31)
                                        if (((30 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&volume_adjust, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_main_checked = (volume_adjust + __cs_local_main_volume) <= 0;
tmain_31:
IF(0,31,tmain_32)
                                        __cs_mutex_unlock(&daemon_mutex, 0);
                                        ;
                                                        ;
                                        static _Bool __cs_local_main___cs_tmp_if_cond_5;
                                        __cs_local_main___cs_tmp_if_cond_5 = __cs_local_main_checked;
                                        if (__cs_local_main___cs_tmp_if_cond_5)
                                                        {
tmain_32:
IF(0,32,tmain_33)
                                        __cs_mutex_lock(&daemon_mutex, 0);
tmain_33:
                                        if (((33 == __cs_pc_cs[0]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                                {
                                        __CPROVER_set_field(&volume_adjust, "dr_write", 1);
                                                                }
IF(0,33,tmain_34)
                                        if (((33 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&volume_adjust, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        volume_adjust = 0;
tmain_34:
IF(0,34,tmain_35)
                                        __cs_mutex_unlock(&daemon_mutex, 0);
                                        __cs_local_main_volume = 1;
                                                        }
                                        __CPROVER_assume(__cs_pc_cs[0] >= 35);
                                                        ;
                                        ;
                                                        ;
                                        static signed int __cs_local_main___cs_temporary_0;
                                        __cs_local_main___cs_temporary_0 = 0;
                                        __cs_local_main___cs_temporary_0 = __cs_local_main_volume;
tmain_35:
IF(0,35,tmain_36)
                                        if (((35 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&volume_adjust, "dr_write"))
                                                                __cs_dataraceNotDetected = 0;
                                        __cs_local_main_volume = __cs_local_main___cs_temporary_0 + volume_adjust;
tmain_36:
IF(0,36,tmain_37)
                                        __cs_mutex_lock(&daemon_mutex, 0);
                                                        {
                                        static signed int __cs_param_mpd_status_set_volume_volume;
                                        __cs_param_mpd_status_set_volume_volume = __cs_local_main_volume;
tmain_37:
                                        if (((37 == __cs_pc_cs[0]) & __cs_dataraceDetectionStarted) & (!__cs_dataraceSecondThread))
                                                                {
                                        __CPROVER_set_field(&_volume, "dr_write", 1);
                                                                }
IF(0,37,tmain_38)
                                        if (((37 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&_volume, "dr_write"))
                                                                        __cs_dataraceNotDetected = 0;
                                        _volume = __cs_param_mpd_status_set_volume_volume;
                                        __exit__mpd_status_set_volume_3_1:
                                                                __CPROVER_assume(__cs_pc_cs[0] >= 38);
                                        ;
                                                                ;
                                                        }
                                        ;
tmain_38:
IF(0,38,tmain_39)
                                        __cs_mutex_unlock(&daemon_mutex, 0);
                                                }
                                        ;
tmain_39:
IF(0,39,tmain_40)
                                        if (((39 == __cs_pc[0]) & __cs_dataraceSecondThread) & __CPROVER_get_field(&leaving, "dr_write"))
                                                        __cs_dataraceNotDetected = 0;
                                        __CPROVER_assume(
                                        !(leaving == 0));
                                        __exit_loop_4:
                                                __CPROVER_assume(__cs_pc_cs[0] >= 40);
                                        ;
                                                ;
tmain_40:
IF(0,40,tmain_41)
                                        __cs_join(__cs_local_main_Lkeys, (void **) 0);
tmain_41:
IF(0,41,tmain_42)
                                        __cs_join(__cs_local_main_g15display, (void **) 0);
tmain_42:
IF(0,42,tmain_43)
                                        __cs_mutex_destroy(&daemon_mutex);
                                        goto __exit_main;
                                                ;
                                        __exit_main:
                                                __CPROVER_assume(__cs_pc_cs[0] >= 43);
                                        ;
                                                ;
tmain_43: 
                                        __cs_exit(0, 0);
                                        }
                                        int main(void)
                                        {
                                        __CPROVER_field_decl_global("dr_write", (_Bool) 0);
                                        unsigned __CPROVER_bitvector[3] __cs_dr_ts;
                                        __CPROVER_assume(__cs_dr_ts <= 7);
/* round  0 */
/* main */
                                        unsigned __CPROVER_bitvector[6] __cs_tmp_t0_r0;
                                        __cs_pc_cs[0] = __cs_tmp_t0_r0;
                                        __CPROVER_assume(__cs_pc_cs[0] > 0);
                                        __CPROVER_assume(__cs_pc_cs[0] <= 43);
                                        if (__cs_dr_ts == 0)
                                                        __cs_dataraceDetectionStarted = 1;
                                        main_thread();
                                        if (__cs_dataraceDetectionStarted)
                                                        __cs_dataraceSecondThread = 1;
                                        __cs_pc[0] = __cs_pc_cs[0];
/* Lkeys_thread_0 */
                                        unsigned __CPROVER_bitvector[4] __cs_tmp_t1_r0;
                                        if (__cs_dataraceContinue & __cs_active_thread[1])
                                                {
                                        __cs_pc_cs[1] = __cs_tmp_t1_r0;
                                        __CPROVER_assume(__cs_pc_cs[1] <= 12);
                                        if (__cs_dr_ts == 1)
                                                                __cs_dataraceDetectionStarted = 1;
                                        Lkeys_thread_0(__cs_threadargs[1]);
                                        if (__cs_dataraceSecondThread & (__cs_tmp_t1_r0 > __cs_pc[1]))
                                                                __cs_dataraceContinue = 0;
                                        if (__cs_dataraceDetectionStarted)
                                                                __cs_dataraceSecondThread = 1;
                                        __cs_pc[1] = __cs_pc_cs[1];
                                                }
/* event_key_thread_0 */
                                        unsigned __CPROVER_bitvector[4] __cs_tmp_t2_r0;
                                        if (__cs_dataraceContinue & __cs_active_thread[2])
                                                {
                                        __cs_pc_cs[2] = __cs_tmp_t2_r0;
                                        __CPROVER_assume(__cs_pc_cs[2] <= 10);
                                        if (__cs_dr_ts == 2)
                                                                __cs_dataraceDetectionStarted = 1;
                                        event_key_thread_0(__cs_threadargs[2]);
                                        if (__cs_dataraceSecondThread & (__cs_tmp_t2_r0 > __cs_pc[2]))
                                                                __cs_dataraceContinue = 0;
                                        if (__cs_dataraceDetectionStarted)
                                                                __cs_dataraceSecondThread = 1;
                                        __cs_pc[2] = __cs_pc_cs[2];
                                                }
/* g15display_thread_0 */
                                        unsigned __CPROVER_bitvector[3] __cs_tmp_t3_r0;
                                        if (__cs_dataraceContinue & __cs_active_thread[3])
                                                {
                                        __cs_pc_cs[3] = __cs_tmp_t3_r0;
                                        __CPROVER_assume(__cs_pc_cs[3] <= 4);
                                        if (__cs_dr_ts == 3)
                                                                __cs_dataraceDetectionStarted = 1;
                                        g15display_thread_0(__cs_threadargs[3]);
                                        if (__cs_dataraceSecondThread & (__cs_tmp_t3_r0 > __cs_pc[3]))
                                                                __cs_dataraceContinue = 0;
                                        if (__cs_dataraceDetectionStarted)
                                                                __cs_dataraceSecondThread = 1;
                                        __cs_pc[3] = __cs_pc_cs[3];
                                                }
/* round  1 */
/* main */
                                        unsigned __CPROVER_bitvector[6] __cs_tmp_t0_r1;
                                        if (((__cs_dr_ts > 0) & __cs_dataraceContinue) & __cs_active_thread[0])
                                                {
                                        __cs_pc_cs[0] = __cs_pc[0] + __cs_tmp_t0_r1;
                                        __CPROVER_assume(__cs_pc_cs[0] >= __cs_pc[0]);
                                        __CPROVER_assume(__cs_pc_cs[0] <= 43);
                                        if (__cs_dr_ts == 4)
                                                                __cs_dataraceDetectionStarted = 1;
                                        main_thread();
                                        if (__cs_dataraceSecondThread & (__cs_tmp_t0_r1 > __cs_pc[0]))
                                                                __cs_dataraceContinue = 0;
                                        if (__cs_dataraceDetectionStarted)
                                                                __cs_dataraceSecondThread = 1;
                                        __cs_pc[0] = __cs_pc_cs[0];
                                                }
/* Lkeys_thread_0 */
                                        unsigned __CPROVER_bitvector[4] __cs_tmp_t1_r1;
                                        if (((__cs_dr_ts > 1) & __cs_dataraceContinue) & __cs_active_thread[1])
                                                {
                                        __cs_pc_cs[1] = __cs_pc[1] + __cs_tmp_t1_r1;
                                        __CPROVER_assume(__cs_pc_cs[1] >= __cs_pc[1]);
                                        __CPROVER_assume(__cs_pc_cs[1] <= 12);
                                        if (__cs_dr_ts == 5)
                                                                __cs_dataraceDetectionStarted = 1;
                                        Lkeys_thread_0(__cs_threadargs[1]);
                                        if (__cs_dataraceSecondThread & (__cs_tmp_t1_r1 > __cs_pc[1]))
                                                                __cs_dataraceContinue = 0;
                                        if (__cs_dataraceDetectionStarted)
                                                                __cs_dataraceSecondThread = 1;
                                        __cs_pc[1] = __cs_pc_cs[1];
                                                }
/* event_key_thread_0 */
                                        unsigned __CPROVER_bitvector[4] __cs_tmp_t2_r1;
                                        if (((__cs_dr_ts > 2) & __cs_dataraceContinue) & __cs_active_thread[2])
                                                {
                                        __cs_pc_cs[2] = __cs_pc[2] + __cs_tmp_t2_r1;
                                        __CPROVER_assume(__cs_pc_cs[2] >= __cs_pc[2]);
                                        __CPROVER_assume(__cs_pc_cs[2] <= 10);
                                        if (__cs_dr_ts == 6)
                                                                __cs_dataraceDetectionStarted = 1;
                                        event_key_thread_0(__cs_threadargs[2]);
                                        if (__cs_dataraceSecondThread & (__cs_tmp_t2_r1 > __cs_pc[2]))
                                                                __cs_dataraceContinue = 0;
                                        if (__cs_dataraceDetectionStarted)
                                                                __cs_dataraceSecondThread = 1;
                                        __cs_pc[2] = __cs_pc_cs[2];
                                                }
/* g15display_thread_0 */
                                        unsigned __CPROVER_bitvector[3] __cs_tmp_t3_r1;
                                        if (((__cs_dr_ts > 3) & __cs_dataraceContinue) & __cs_active_thread[3])
                                                {
                                        __cs_pc_cs[3] = __cs_pc[3] + __cs_tmp_t3_r1;
                                        __CPROVER_assume(__cs_pc_cs[3] >= __cs_pc[3]);
                                        __CPROVER_assume(__cs_pc_cs[3] <= 4);
                                        if (__cs_dr_ts == 7)
                                                                __cs_dataraceDetectionStarted = 1;
                                        g15display_thread_0(__cs_threadargs[3]);
                                        if (__cs_dataraceSecondThread & (__cs_tmp_t3_r1 > __cs_pc[3]))
                                                                __cs_dataraceContinue = 0;
                                        if (__cs_dataraceDetectionStarted)
                                                                __cs_dataraceSecondThread = 1;
                                        __cs_pc[3] = __cs_pc_cs[3];
                                                }
                                        unsigned __CPROVER_bitvector[6] __cs_tmp_t0_r2;
                                        if (((__cs_dr_ts > 0) & __cs_dataraceContinue) & __cs_active_thread[0])
                                                {
                                        __cs_pc_cs[0] = __cs_pc[0] + __cs_tmp_t0_r2;
                                        __CPROVER_assume(__cs_pc_cs[0] >= __cs_pc[0]);
                                        __CPROVER_assume(__cs_pc_cs[0] <= 43);
                                        main_thread();
                                                }
                                        __CPROVER_assert(__cs_dataraceNotDetected, "Data race failure");
                                        return 0;
                                        }
                                        
